DATA: data/data.pkl
IMG_HOSPET: images/HOSPET.jpeg
IMG_MBF: images/MBF.jpg
IMG_VOPTIMAI: images/VOPTIMAI.png
LAMBDA_REG: 0.05
OPTIM_STEPS: 30
Optimisation:
  Eta CO:
    output_param: FURNACETOPGASANALYSISCO2ETACO
    model: packages/furnace-data/furnace_data/assets/models/etaco_model.pkl
    scaling: packages/furnace-data/furnace_data/assets/models/etaco_scaler.pkl
    maxmin: -1.0
    control_params:
    - HOT BLAST PRESSUREBAR
    - TOPPRESSUREBAR
    - HOT BLAST TEMP.OC
    - STEAMKGS/HR.
    - HOT BLAST VOLUMENM3/HR.
    - O2 ENRICHMENT %
    input_params:
      Coke:
      - COKE_ASH%
      - COKE_FC%
      - COKE_IM%
      - COKE_MOIST%
      - COKE_VM%
      - COKE_CALC_MT
      - COKE_DISCHARGE_TIME
      NutCoke:
      - NUTCOKE_ASH%
      - NUTCOKE_FC%
      - NUTCOKE_IM%
      - NUTCOKE_MOIST%
      - NUTCOKE_VM%
      - NUTCOKE_CALC_MT
      PCI:
      - PCI_ASH%
      - PCI_FC%
      - PCI_IM%
      - PCI_VM%
      - PCI_CALC_MT
      Ore:
      - ORE_AL2O3%
      - ORE_CAO%
      - ORE_FE(T)%
      - ORE_K2O%
      - ORE_LOI%
      - ORE_MGO%
      - ORE_MNO%
      - ORE_CALC_MT
      - ORE_NA2O%
      - ORE_P%
      - ORE_SIO2%
      - ORE_TIO2%
      - ORE_TM%
      Sinter:
      - SINTER_AL2O3%
      - SINTER_CAO%
      - SINTER_COLD_STRENGTH_AI
      - SINTER_COLD_STRENGTH_TI
      - SINTER_FE(T)%
      - SINTER_FEO%
      - SINTER_HOT_STRENGTH_RDI
      - SINTER_HOT_STRENGTH_RI
      - SINTER_K2O%
      - SINTER_MGO%
      - SINTER_MNO%
      - SINTER_CALC_MT
      - SINTER_NA2O%
      - SINTER_P%
      - SINTER_SIO2%
      - SINTER_BASICITY
      - SINTER_TIO2%
      Pellet:
      - PELLET_PCT_CAO
      - TOTAL_PELLET_CALC_MT
      - PELLET_PCT_AL2O3
      - PELLET_PCT_FE2O3
      - PELLET_PCT_K2O
      - PELLET_PCT_LOI
      - PELLET_PCT_MGO
      - PELLET_PCT_MNO
      - PELLET_PCT_NA2O
      - PELLET_PCT_P
      - PELLET_PCT_SIO2
      - PELLET_PCT_TIO2
      - PELLET_PCT_TM
      Flux:
      - FLUX_AL2O3%
      - FLUX_CAO%
      - FLUX_FE2O3%
      - FLUX_LOI%
      - FLUX_MGO%
      - FLUX_CALC_MT
      - FLUX_SIO2%
      - FLUX_TM%
      Burden:
      - WEIGHTED_COKE_ANGLE
      - WEIGHTED_NON_COKE_ANGLE
      - TOTAL_COKE_PORTIONS
      - TOTAL_NON_COKE_PORTIONS
      - NON_COKE_DISCHARGE_TIME
      Temperature:
      - BELLY_TEMP_A
      - BELLY_TEMP_C
      - BELLY_TEMP_D
      - BOSH_TEMP_A
      - BOSH_TEMP_B
      - BOSH_TEMP_C
      - BOSH_TEMP_D
      - LOWER_STACK_TEMP_A
      - LOWER_STACK_TEMP_B
      - LOWER_STACK_TEMP_C
      - LOWER_STACK_TEMP_D
      - FTG_UPTAKE_TEMP_AVG
      - FTG_UPTAKE_TEMP_B
      - FTG_UPTAKE_TEMP_A
      - FTG_UPTAKE_TEMP_C
      - FTG_UPTAKE_TEMP_D
      - HEARTH_TEMP_A
      - HEARTH_TEMP_B
      - HEARTH_TEMP_C
      - HEARTH_TEMP_D
      Other:
      - FURNACE TOP GAS ANALYSISH2%
  Production Rate:
    output_param: PRODUCTIONTONNESPERHR
    model: packages/furnace-data/furnace_data/assets/models/productionrate_model.pkl
    scaling: packages/furnace-data/furnace_data/assets/models/productionrate_scaler.pkl
    maxmin: -1.0
    control_params:
    - HOT BLAST PRESSUREBAR
    - TOPPRESSUREBAR
    - HOT BLAST TEMP.OC
    - STEAMKGS/HR.
    - HOT BLAST VOLUMENM3/HR.
    - PCI_KG/THM
    - O2 ENRICHMENT %
    input_params:
      Coke:
      - COKE_ASH%
      - COKE_FC%
      - COKE_IM%
      - COKE_MOIST%
      - COKE_VM%
      - COKE_CALC_MT
      - COKE_DISCHARGE_TIME
      NutCoke:
      - NUTCOKE_ASH%
      - NUTCOKE_FC%
      - NUTCOKE_IM%
      - NUTCOKE_MOIST%
      - NUTCOKE_VM%
      - NUTCOKE_CALC_MT
      PCI:
      - PCI_ASH%
      - PCI_FC%
      - PCI_IM%
      - PCI_VM%
      - PCI_CALC_MT
      Ore:
      - ORE_AL2O3%
      - ORE_CAO%
      - ORE_FE(T)%
      - ORE_K2O%
      - ORE_LOI%
      - ORE_MGO%
      - ORE_MNO%
      - ORE_CALC_MT
      - ORE_NA2O%
      - ORE_P%
      - ORE_SIO2%
      - ORE_TIO2%
      - ORE_TM%
      Sinter:
      - SINTER_AL2O3%
      - SINTER_CAO%
      - SINTER_COLD_STRENGTH_AI
      - SINTER_COLD_STRENGTH_TI
      - SINTER_FE(T)%
      - SINTER_FEO%
      - SINTER_HOT_STRENGTH_RDI
      - SINTER_HOT_STRENGTH_RI
      - SINTER_K2O%
      - SINTER_MGO%
      - SINTER_MNO%
      - SINTER_CALC_MT
      - SINTER_NA2O%
      - SINTER_P%
      - SINTER_SIO2%
      - SINTER_BASICITY
      - SINTER_TIO2%
      Pellet:
      - PELLET_PCT_CAO
      - TOTAL_PELLET_CALC_MT
      - PELLET_PCT_AL2O3
      - PELLET_PCT_FE2O3
      - PELLET_PCT_K2O
      - PELLET_PCT_LOI
      - PELLET_PCT_MGO
      - PELLET_PCT_MNO
      - PELLET_PCT_NA2O
      - PELLET_PCT_P
      - PELLET_PCT_SIO2
      - PELLET_PCT_TIO2
      - PELLET_PCT_TM
      Flux:
      - FLUX_AL2O3%
      - FLUX_CAO%
      - FLUX_FE2O3%
      - FLUX_LOI%
      - FLUX_MGO%
      - FLUX_CALC_MT
      - FLUX_SIO2%
      - FLUX_TM%
      Burden:
      - WEIGHTED_COKE_ANGLE
      - WEIGHTED_NON_COKE_ANGLE
      - TOTAL_COKE_PORTIONS
      - TOTAL_NON_COKE_PORTIONS
      - NON_COKE_DISCHARGE_TIME
      Other:
      - FURNACE TOP GAS ANALYSISH2%
      - CHARGES/HRS.
      - STOCKRODLEVEL
  UnitCost:
    control_params:
    - HOT BLAST PRESSUREBAR
    - TOPPRESSUREBAR
    - HOT BLAST TEMP.OC
    - STEAMKGS/HR.
    - HOT BLAST VOLUMENM3/HR.
    - O2 ENRICHMENT %
    input_params:
      Coke:
      - COKE_VM%
      - COKE_ASH%
      - COKE_IM%
      - COKE_FC%
      - COKE_MOIST%
      - COKE_CALC_MT
      NutCoke:
      - NUTCOKE_MOIST%
      - NUTCOKE_CALC_MT
      - NUTCOKE_VM%
      - NUTCOKE_IM%
      - NUTCOKE_FC%
      - NUTCOKE_ASH%
      PCI:
      - PCI_FC%
      - PCI_ASH%
      - PCI_VM%
      - PCI_IM%
      - PCI_CALC_MT
      Ore:
      - GEOMIN TYPE
      - ORE_FE(T)%
      - ORE_LOI%
      - ORE_TM%
      - ORE_MGO%
      - ORE_NA2O%
      - ORE_P%
      - ORE_TIO2%
      - ORE_AL2O3%
      - ORE_SIO2%
      - ORE_MNO%
      - ORE_CAO%
      - ORE_K2O%
      - ORE_CALC_MT
      Sinter:
      - SINTER_HOT_STRENGTH_RI
      - SINTER_HOT_STRENGTH_RDI
      - SINTER_COLD_STRENGTH_AI
      - SINTER_COLD_STRENGTH_TI
      - SINTER_P%
      - SINTER_SIO2%
      - SINTER_MGO%
      - SINTER_FEO%
      - SINTER_AL2O3%
      - SINTER_NA2O%
      - SINTER_TIO2%
      - SINTER_FE(T)%
      - SINTER_CAO%
      - SINTER_K2O%
      - SINTER_BASICITY
      - SINTER_MNO%
      - SINTER_CALC_MT
      Pellet:
      - PELLET_PCT_SIO2
      - PELLET_PCT_AL2O3
      - PELLET_PCT_FE2O3
      - PELLET_PCT_MGO
      - PELLET_PCT_TIO2
      - PELLET_PCT_NA2O
      - TOTAL_PELLET_CALC_MT
      - PELLET_PCT_K2O
      - PELLET_PCT_TM
      - PELLET_PCT_LOI
      - PELLET_PCT_MNO
      - PELLET_PCT_CAO
      - PELLET_PCT_P
      Flux:
      - FLUX_TM%
      - FLUX_SIO2%
      - FLUX_FE2O3%
      - FLUX_AL2O3%
      - FLUX_LOI%
      - FLUX_MGO%
      - FLUX_CAO%
      - FLUX_CALC_MT
      Burden:
      - COKE_DISCHARGE_TIME
      - WEIGHTED_COKE_ANGLE
      - TOTAL_COKE_PORTIONS
      - NON_COKE_DISCHARGE_TIME
      - WEIGHTED_NON_COKE_ANGLE
      - TOTAL_NON_COKE_PORTIONS
      Other:
      - CHARGES/HRS.
      - STOCKRODLEVEL
      - FURNACE TOP GAS ANALYSISH2%
    maxmin: 1.0
    model: packages/furnace-data/furnace_data/assets/models/unitcost_opt_dec.pkl
    output_param: UNITCOST LAKHS/THM
    scaling: packages/furnace-data/furnace_data/assets/models/unitcost_scaler_dec.pkl
TIMESTEPS: 3
field_mapping:
  Sinter_SP_02_Basicity: SINTER_BASICITY
  coke_ash_pct: COKE_ASH%
  coke_fc_pct: COKE_FC%
  coke_im_pct: COKE_IM%
  coke_moist_pct: COKE_MOIST%
  coke_vm_pct: COKE_VM%
  coke_mt: COKE_CALC_MT
  flux_al2o3_pct: FLUX_AL2O3%
  flux_cao_pct: FLUX_CAO%
  flux_fe2o3_pct: FLUX_FE2O3%
  flux_loi_pct: FLUX_LOI%
  flux_mgo_pct: FLUX_MGO%
  flux_mt: FLUX_CALC_MT
  flux_sio2_pct: FLUX_SIO2%
  flux_tm_pct: FLUX_TM%
  GeominType: GEOMIN TYPE
  nutcoke_ash_pct: NUTCOKE_ASH%
  nutcoke_fc_pct: NUTCOKE_FC%
  nutcoke_im_pct: NUTCOKE_IM%
  nutcoke_moist_pct: NUTCOKE_MOIST%
  nutcoke_prime_mt: NUTCOKE_CALC_MT
  nutcoke_vm_pct: NUTCOKE_VM%
  ore_al2o3_pct: ORE_AL2O3%
  ore_cao_pct: ORE_CAO%
  ore_fe_total_pct: ORE_FE(T)%
  ore_k2o_pct: ORE_K2O%
  ore_loi_pct: ORE_LOI%
  ore_mgo_pct: ORE_MGO%
  ore_mno_pct: ORE_MNO%
  ore_na2o_pct: ORE_NA2O%
  ore_p_pct: ORE_P%
  ore_sio2_pct: ORE_SIO2%
  ore_tio2_pct: ORE_TIO2%
  ore_tm_pct: ORE_TM%
  ore_mt: ORE_CALC_MT
  pci2_ash_pct: PCI_ASH%
  pci2_fc_pct: PCI_FC%
  pci2_im_pct: PCI_IM%
  pci2_vm_pct: PCI_VM%
  pci2_mt: PCI_CALC_MT
  sinter_al2o3_pct: SINTER_AL2O3%
  sinter_cao_pct: SINTER_CAO%
  sinter_cold_strength_ai: SINTER_COLD_STRENGTH_AI
  sinter_cold_strength_ti: SINTER_COLD_STRENGTH_TI
  sinter_hot_strength_ri: SINTER_HOT_STRENGTH_RI
  sinter_fe_total_pct: SINTER_FE(T)%
  sinter_feo_pct: SINTER_FEO%
  sinter_hot_strength_rdi: SINTER_HOT_STRENGTH_RDI
  sinter_k2o_pct: SINTER_K2O%
  sinter_mgo_pct: SINTER_MGO%
  sinter_mno_pct: SINTER_MNO%
  sinter_na2o_pct: SINTER_NA2O%
  sinter_p_pct: SINTER_P%
  sinter_sio2_pct: SINTER_SIO2%
  sinter_tio2_pct: SINTER_TIO2%
  sinter_sp_02_basicity: SINTER_BASICITY
  sinter_mt: SINTER_CALC_MT
  pellet_cao_pct: PELLET_PCT_CAO
  pellet_mt: TOTAL_PELLET_CALC_MT
  pellet_pct_al2o3: PELLET_PCT_AL2O3
  pellet_pct_fe2o3: PELLET_PCT_FE2O3
  pellet_pct_k2o: PELLET_PCT_K2O
  pellet_pct_loi: PELLET_PCT_LOI
  pellet_pct_mgo: PELLET_PCT_MGO
  pellet_pct_mno: PELLET_PCT_MNO
  pellet_pct_na2o: PELLET_PCT_NA2O
  pellet_pct_p: PELLET_PCT_P
  pellet_pct_sio2: PELLET_PCT_SIO2
  pellet_pct_tio2: PELLET_PCT_TIO2
  pellet_pct_tm: PELLET_PCT_TM
  charges_per_hr: CHARGES/HRS.
  stock_rod_level: STOCKRODLEVEL
  furnace_top_gas_analysis_h2_pct: FURNACE TOP GAS ANALYSISH2%
  belly_a_c: BELLY_TEMP_A
  belly_c_c: BELLY_TEMP_C
  belly_d_c: BELLY_TEMP_D
  bosh_a_c: BOSH_TEMP_A
  bosh_b_c: BOSH_TEMP_B
  bosh_c_c: BOSH_TEMP_C
  bosh_d_c: BOSH_TEMP_D
  lower_stack_a_c: LOWER_STACK_TEMP_A
  lower_stack_b_c: LOWER_STACK_TEMP_B
  lower_stack_c_c: LOWER_STACK_TEMP_C
  lower_stack_d_c: LOWER_STACK_TEMP_D
  ftg_uptake_avg_c: FTG_UPTAKE_TEMP_AVG
  ftg_uptake_bt12_c: FTG_UPTAKE_TEMP_B
  ftg_uptake_cat16_c: FTG_UPTAKE_TEMP_A
  ftg_uptake_ct08_c: FTG_UPTAKE_TEMP_C
  ftg_uptake_dt04_c: FTG_UPTAKE_TEMP_D
  hearth_pad_4d3_c: HEARTH_TEMP_A
  hearth_pad_b5d4_c: HEARTH_TEMP_B
  hearth_pad_c5d7_c: HEARTH_TEMP_C
  hearth_pad_d6d1_c: HEARTH_TEMP_D
influxdb_ml_database:
  database: ML DATASET
  measurements: rm_charge_dataset
  time_range: last 1 month