"""Database-backed quick-skill registry for FurnaceMind.

This module is the bridge between the ``furnace_mind.skills`` SQL table and the
quick-skill buttons shown in the FurnaceMind chat UI. A database row controls the
human-facing configuration: name, symbol, active state, instruction text, and any
supporting ``.md`` context files. Python keeps ownership of execution by mapping
rows only to a small whitelist of ``SkillEngine`` handlers.

That split is deliberate. Operators can add, hide, rename, and tune prompt-based
skills from the UI/database, while the application still avoids running arbitrary
code or reading arbitrary files from values stored in SQL. If the database is
empty or unavailable, the registry falls back to the built-in skills so the chat
screen remains usable.
"""

from __future__ import annotations

import math
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from datetime import date, timezone
from pathlib import Path
from typing import Any

from furnace_data.runtime_paths import get_repo_root, runtime_path

_COPILOT_DATA_DIR = get_repo_root() / "src" / "storage" / "furnacemind"
_SLUG_RE = re.compile(r"[^a-z0-9_]+")
_SKILL_SEARCH_CONTEXT_CHARS = 6_000
_RETRIEVED_SKILL_CONTEXT_CHARS = 8_000
_SEMANTIC_SKILL_LIMIT = 2
_SEMANTIC_SKILL_MIN_SCORE = 0.42


@dataclass(frozen=True)
class SkillDefinition:
    """Normalized runtime configuration for one FurnaceMind quick skill.

    The UI and chat pipeline should not care whether a skill came from a SQL row
    or from the built-in fallback list. This dataclass gives both sources the
    same shape. ``slug`` is the stable application key used for Streamlit state
    and prompt context. ``handler`` names a whitelisted ``SkillEngine`` method
    for built-in/code-backed skills; prompt-only DB skills leave it blank and use
    ``instruction`` plus optional ``context_files`` instead.
    """

    skill_id: str
    slug: str
    name: str
    symbol: str = ""
    description: str = ""
    instruction: str = ""
    source_type: str = "built_in"
    handler: str = ""
    display_template: str = ""
    context_files: tuple[str, ...] = ()
    order: int = 1000
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def button_label(self) -> str:
        """Return the compact label displayed on the quick-skill button."""
        return f"{self.symbol} {self.name}".strip()


@dataclass(frozen=True)
class SkillExecution:
    """Prompt, display label, and extra context generated by a skill click.

    ``prompt`` becomes the queued user message, ``display`` is what the chat UI
    shows for that click, and ``skill_context`` is injected into the agent prompt
    so DB-provided instructions and uploaded skill files can guide the answer.
    """

    prompt: str
    display: str
    skill_id: str
    skill_context: str = ""


class _SafeFormatDict(dict[str, str]):
    """Dictionary used by ``str.format_map`` to preserve unknown placeholders."""

    def __missing__(self, key: str) -> str:
        return "{" + key + "}"


_BUILTIN_SKILLS: tuple[SkillDefinition, ...] = (
    SkillDefinition(
        skill_id="optimise",
        slug="optimise",
        name="Unit Cost",
        symbol="â‚¹",
        description="Compare recent operating state against best-shift cost targets.",
        handler="optimise_prompt",
        display_template="Unit Cost - last 30 days vs best-shift targets",
        context_files=("SKILLS_BESTSHIFT.md", "SKILLS_OPTIMISE.md"),
        order=10,
    ),
    SkillDefinition(
        skill_id="shift_to_best",
        slug="shift_to_best",
        name="Shift to Best",
        symbol="â†—",
        description="Compare the last completed shift against best-shift targets.",
        handler="shift_to_best_prompt",
        display_template="Shift to Best: {shift_date}, Shift {shift_label}",
        context_files=("SKILLS_BESTSHIFT.md",),
        order=20,
    ),
    SkillDefinition(
        skill_id="heatload",
        slug="heatload",
        name="Heatloads",
        symbol="ðŸ”¥",
        description="Check recent heatload and skin-temperature behavior.",
        handler="heatload_prompt",
        display_template="Heatloads - last 8h vs 2-month baseline",
        context_files=("SKILLS_HEATLOAD.md",),
        order=30,
    ),
)

_HANDLER_ALIASES = {
    "optimise": "optimise_prompt",
    "optimize": "optimise_prompt",
    "unit_cost": "optimise_prompt",
    "shift_to_best": "shift_to_best_prompt",
    "heatload": "heatload_prompt",
    "heatloads": "heatload_prompt",
    "shift_report": "shift_report_prompt",
}

_SUPPORTED_HANDLERS = {
    "optimise_prompt",
    "shift_to_best_prompt",
    "heatload_prompt",
    "shift_report_prompt",
}


def _slugify(value: str) -> str:
    """Return a stable lowercase key for DB matching and Streamlit state.

    Skill names are editable, and DB rows may contain spaces or punctuation. The
    registry normalizes them to one simple slug before comparing selected buttons
    or building session-state keys.
    """
    normalized = _SLUG_RE.sub("_", str(value or "").strip().lower()).strip("_")
    return normalized or "skill"


def _metadata_for(row: Any) -> dict[str, Any]:
    """Return the JSON metadata payload for a reflected SQLAlchemy skill row.

    The relational model exposes database ``metadata`` as ``metadata_json`` to
    avoid clashing with SQLAlchemy's own ``metadata`` attribute. This helper keeps
    that detail in one place and treats malformed/null metadata as empty config.
    """
    metadata = getattr(row, "metadata_json", None)
    return metadata if isinstance(metadata, dict) else {}


def _string_value(value: Any, default: str = "") -> str:
    """Coerce optional DB/metadata values to a stripped string.

    Reflected rows and JSON metadata can carry ``None``, numbers, or blank text.
    Normalizing here prevents every call site from repeating defensive checks.
    """
    if value is None:
        return default
    stripped = str(value).strip()
    return stripped if stripped else default


def _int_value(value: Any, default: int) -> int:
    """Coerce optional DB/metadata values to ``int`` with a safe fallback."""
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _context_files(value: Any) -> tuple[str, ...]:
    """Return safe markdown context filenames configured for a skill.

    Skill metadata may contain one filename or a list of filenames. Only basename
    ``.md`` files are accepted, so a database value cannot traverse directories or
    point the registry at arbitrary files outside ``src/storage/furnacemind``.
    Duplicate filenames are removed while preserving the configured order.
    """
    if isinstance(value, str):
        raw_files = [value]
    elif isinstance(value, (list, tuple, set)):
        raw_files = list(value)
    else:
        raw_files = []

    filenames: list[str] = []
    for item in raw_files:
        filename = Path(str(item or "").strip()).name
        if filename and filename.lower().endswith(".md"):
            filenames.append(filename)
    return tuple(dict.fromkeys(filenames))


def _read_context_file(filename: str, *, max_chars: int = 14_000) -> str:
    """Read bounded markdown context for a skill from the approved storage folder.

    Missing files, empty files, and read errors intentionally return an empty
    string. The registry should degrade to the DB instruction instead of breaking
    the chat UI because an optional support file is absent. The character limit
    prevents a large uploaded skill file from flooding the agent prompt.
    """
    try:
        safe_name = Path(filename).name
        runtime_path_candidate = runtime_path(
            "uploads", "furnacemind", "skills", safe_name
        )
        path = (
            runtime_path_candidate
            if runtime_path_candidate.exists()
            else _COPILOT_DATA_DIR / safe_name
        )
        if not path.exists():
            return ""
        text = path.read_text(encoding="utf-8", errors="ignore").strip()
        if not text:
            return ""
        if len(text) <= max_chars:
            return text
        return text[:max_chars].rstrip() + "\n\n[...truncated...]"
    except Exception:
        return ""


def _format_template(template: str, *, shift_date: date, shift_label: str) -> str:
    """Format skill templates with shift fields while tolerating bad input.

    Built-in and DB skills can use placeholders such as ``{shift_date}`` and
    ``{shift_label}`` in button display text or prompt templates. Unknown
    placeholders are kept visible, and malformed templates fall back to the raw
    template so a bad DB value does not crash the UI.
    """
    values = _SafeFormatDict(
        shift_date=str(shift_date),
        shift_label=str(shift_label),
    )
    try:
        return template.format_map(values)
    except Exception:
        return template


def _bounded_text(text: str, *, max_chars: int) -> str:
    """Return stripped text capped to a prompt-safe character budget.

    Skill instructions and markdown files can be edited outside this module. A
    small, explicit cap keeps semantic matching and prompt injection from being
    dominated by one oversized support file while still leaving a visible marker
    when text was shortened.
    """
    clean = str(text or "").strip()
    if len(clean) <= max_chars:
        return clean
    return clean[:max_chars].rstrip() + "\n\n[...truncated...]"


def _embed_text(embedding_client: Any, text: str, *, input_type: str) -> list[float]:
    """Embed text while tolerating embedding clients without ``input_type``.

    Production uses ``CloudEmbeddingClient.embed_text(..., input_type=...)`` for
    retrieval-optimized Voyage embeddings. Tests and local fakes may implement a
    smaller method signature, so this helper falls back to ``embed_text(text)``.
    """
    try:
        vector = embedding_client.embed_text(text, input_type=input_type)
    except TypeError:
        vector = embedding_client.embed_text(text)
    return [float(value) for value in vector]


def _cosine_similarity(vector_a: Sequence[float], vector_b: Sequence[float]) -> float:
    """Return cosine similarity for two embedding vectors.

    Invalid, empty, or mismatched vectors score ``0.0``. Retrieval should degrade
    quietly instead of breaking chat when an embedding provider returns an
    unexpected shape.
    """
    if not vector_a or not vector_b or len(vector_a) != len(vector_b):
        return 0.0
    dot = sum(a * b for a, b in zip(vector_a, vector_b, strict=True))
    norm_a = math.sqrt(sum(a * a for a in vector_a))
    norm_b = math.sqrt(sum(b * b for b in vector_b))
    if norm_a <= 0.0 or norm_b <= 0.0:
        return 0.0
    return dot / (norm_a * norm_b)


def _handler_from_metadata(slug: str, metadata: dict[str, Any]) -> str:
    """Resolve DB handler aliases to approved ``SkillEngine`` method names.

    SQL rows may use friendly aliases like ``unit_cost`` or ``heatloads``. The
    returned value is either one of the explicit supported handlers or an empty
    string, which forces the registry down the prompt-only path. This is the main
    guardrail that keeps database configuration from invoking arbitrary methods.
    """
    configured = _string_value(metadata.get("handler") or metadata.get("handler_name"))
    handler = _HANDLER_ALIASES.get(configured, configured)
    if not handler:
        handler = _HANDLER_ALIASES.get(slug, "")
    return handler if handler in _SUPPORTED_HANDLERS else ""


def _definition_from_row(row: Any, *, fallback_order: int) -> SkillDefinition:
    """Convert one SQLAlchemy skill row into a normalized ``SkillDefinition``.

    The skills table has a small stable schema plus a flexible JSON metadata
    column. This function applies defaults, builds the slug, validates the
    handler, sanitizes context-file names, and carries metadata forward for prompt
    templates. Keeping that conversion here makes the rest of the registry work
    with one clean runtime object.
    """
    metadata = _metadata_for(row)
    name = _string_value(getattr(row, "name", None), "Skill")
    raw_slug = _string_value(
        metadata.get("slug")
        or metadata.get("key")
        or metadata.get("skill_slug")
        or getattr(row, "skill_id", None)
        or name
    )
    slug = _slugify(raw_slug)
    handler = _handler_from_metadata(slug, metadata)
    return SkillDefinition(
        skill_id=_string_value(getattr(row, "skill_id", None), slug),
        slug=slug,
        name=name,
        symbol=_string_value(getattr(row, "symbol", None) or metadata.get("symbol"))[
            :8
        ],
        description=_string_value(getattr(row, "description", None)),
        instruction=_string_value(getattr(row, "instruction", None)),
        source_type=_string_value(getattr(row, "source_type", None), "uploaded"),
        handler=handler,
        display_template=_string_value(metadata.get("display_template"), name),
        context_files=_context_files(
            metadata.get("context_files") or metadata.get("skill_files")
        ),
        order=_int_value(
            metadata.get("order") or metadata.get("sort_order"), fallback_order
        ),
        metadata={**metadata},
    )


class SkillRegistry:
    """Load DB-driven quick skills and turn user clicks into agent prompts.

    ``SkillRegistry`` is intentionally narrow: it reads skill definitions from the
    repository, applies the fallback rules, and produces ``SkillExecution``
    payloads for the chat UI. It does not own the sidebar form, database writes,
    or the actual blast-furnace prompt logic.

    Fallback behavior is important: an empty/unavailable table uses built-in
    skills so existing deployments still work, but a populated table with all
    rows inactive returns no skills. That lets admins intentionally disable every
    quick skill from the database.
    """

    def __init__(
        self,
        *,
        engine: Any,
        repository: Any | None = None,
        vector_store: Any | None = None,
    ) -> None:
        """Create a registry around the engine, SQL repository, and vector index.

        ``engine`` provides the existing code-backed skill prompt methods.
        ``repository`` is optional so tests and deployments without the skills
        table can still use built-in fallback definitions. ``vector_store`` is
        optional and, when available, provides Qdrant-backed retrieval for
        additional contextually relevant skills.
        """
        self._engine = engine
        self._repository = repository
        self._vector_store = vector_store
        self.last_error: str | None = None
        self.last_relevance_error: str | None = None
        self.last_context_skill_ids: tuple[str, ...] = ()
        self.last_context_skill_slugs: tuple[str, ...] = ()
        self.using_fallback = repository is None

    def available_skills(self) -> list[SkillDefinition]:
        """Return the quick skills currently available to the chat UI.

        Active SQL rows are preferred. ``None`` from ``_database_definitions``
        means the database cannot provide definitions, so built-ins are returned.
        An empty list means the database intentionally has no active skills.
        """
        definitions = self._database_definitions()
        if definitions is None:
            self.using_fallback = True
            return list(_BUILTIN_SKILLS)
        self.using_fallback = False
        return definitions

    def execute(
        self,
        slug: str,
        *,
        shift_date: date,
        shift_label: str,
    ) -> SkillExecution:
        """Execute the active skill selected by slug.

        This convenience API is used by tests and remains useful for non-UI
        callers. The Streamlit UI already has the selected ``SkillDefinition`` and
        usually calls ``execute_definition`` directly.
        """
        normalized = _slugify(slug)
        for definition in self.available_skills():
            if definition.slug == normalized:
                return self.execute_definition(
                    definition,
                    shift_date=shift_date,
                    shift_label=shift_label,
                )
        raise ValueError(f"Unknown FurnaceMind skill: {slug}")

    def execute_definition(
        self,
        definition: SkillDefinition,
        *,
        shift_date: date,
        shift_label: str,
    ) -> SkillExecution:
        """Build the prompt package for one selected skill definition.

        Handler-backed skills delegate prompt construction to ``SkillEngine``.
        Prompt-only database skills build a text prompt from their instruction or
        ``prompt_template`` metadata. Both paths attach ``skill_context`` so the
        agent receives the DB instruction and configured markdown support files.
        """
        if definition.handler:
            prompt = self._execute_handler(
                definition.handler,
                shift_date=shift_date,
                shift_label=shift_label,
            )
        else:
            prompt = self._prompt_from_instruction(
                definition,
                shift_date=shift_date,
                shift_label=shift_label,
            )

        display = _format_template(
            definition.display_template or definition.name,
            shift_date=shift_date,
            shift_label=shift_label,
        )
        return SkillExecution(
            prompt=prompt,
            display=display,
            skill_id=definition.slug,
            skill_context=self.skill_context(definition),
        )

    def skill_context(self, definition: SkillDefinition) -> str:
        """Build the extra prompt context injected when a skill is used.

        The context starts with the database instruction, then appends each safe
        markdown support file configured in metadata. The returned text is not the
        user-visible message; it is side context for the agent to follow.
        """
        parts: list[str] = []
        if definition.instruction:
            parts.append(
                f"{definition.name} (database skill instruction):\n"
                f"{definition.instruction}"
            )
        for filename in definition.context_files:
            text = _read_context_file(filename)
            if text:
                parts.append(f"{filename} (skill benchmark data):\n{text}")
        return "\n\n---\n\n".join(parts).strip()

    def turn_skill_context(
        self,
        *,
        query: str,
        recent_messages: Iterable[dict[str, Any]] | None = None,
        selected_skill_id: str | None = None,
        selected_skill_context: str | None = None,
        embedding_client: Any | None = None,
        max_retrieved: int = _SEMANTIC_SKILL_LIMIT,
        min_score: float = _SEMANTIC_SKILL_MIN_SCORE,
    ) -> str:
        """Build skill context for one user turn using explicit and semantic picks.

        The user-selected quick skill is always included first and is never
        filtered by relevance. After that, the registry may add a small number of
        active skills whose DB instruction/support files are semantically close
        to the current message plus the last few chat messages. Retrieved skills
        are marked as supporting context so the agent does not treat them as if
        the user clicked those buttons.
        """
        context_skill_ids: list[str] = []
        context_skill_slugs: list[str] = []
        self.last_context_skill_ids = ()
        self.last_context_skill_slugs = ()

        def remember_context_skill(
            definition: SkillDefinition | None,
            raw_skill_id: str | None = None,
        ) -> None:
            if definition is not None:
                if definition.skill_id:
                    context_skill_ids.append(definition.skill_id)
                if definition.slug:
                    context_skill_slugs.append(definition.slug)
                return
            clean = _string_value(raw_skill_id)
            if clean:
                context_skill_ids.append(clean)
                context_skill_slugs.append(_slugify(clean))

        selected_definition = self._definition_for_key(selected_skill_id)
        selected_keys = self._selected_keys(selected_skill_id, selected_definition)
        selected_context = str(selected_skill_context or "").strip()
        if selected_definition is not None and not selected_context:
            selected_context = self.skill_context(selected_definition)

        blocks: list[str] = []
        if selected_context:
            remember_context_skill(selected_definition, selected_skill_id)
            label = (
                selected_definition.name if selected_definition else selected_skill_id
            )
            blocks.append(
                "EXPLICITLY SELECTED SKILL CONTEXT "
                "(always include; do not filter this out):\n"
                f"Selected skill: {label}\n\n{selected_context}"
            )
        elif selected_definition is not None:
            remember_context_skill(selected_definition, selected_skill_id)
            blocks.append(
                "EXPLICITLY SELECTED SKILL CONTEXT "
                "(always include; do not filter this out):\n"
                + self._skill_context_block(selected_definition)
            )

        relevant = self.relevant_skills(
            query=query,
            recent_messages=recent_messages,
            embedding_client=embedding_client,
            exclude_skill_ids=selected_keys,
            max_skills=max_retrieved,
            min_score=min_score,
        )
        if relevant:
            relevant_blocks = []
            for definition, score in relevant:
                remember_context_skill(definition)
                context = _bounded_text(
                    self.skill_context(definition),
                    max_chars=_RETRIEVED_SKILL_CONTEXT_CHARS,
                )
                relevant_blocks.append(
                    self._skill_context_block(
                        definition,
                        context=context,
                        source_label=f"semantic match score={score:.3f}",
                    )
                )
            blocks.append(
                "SEMANTICALLY RELEVANT SKILL CONTEXT "
                "(supporting context only; not user-clicked):\n"
                + "\n\n---\n\n".join(relevant_blocks)
            )

        self.last_context_skill_ids = tuple(dict.fromkeys(context_skill_ids))
        self.last_context_skill_slugs = tuple(dict.fromkeys(context_skill_slugs))
        return "\n\n===\n\n".join(blocks).strip()

    def relevant_skills(
        self,
        *,
        query: str,
        recent_messages: Iterable[dict[str, Any]] | None = None,
        embedding_client: Any | None = None,
        exclude_skill_ids: set[str] | None = None,
        max_skills: int = _SEMANTIC_SKILL_LIMIT,
        min_score: float = _SEMANTIC_SKILL_MIN_SCORE,
    ) -> list[tuple[SkillDefinition, float]]:
        """Return active skills semantically relevant to the current turn.

        The preferred path searches the persisted Qdrant skill index. Returned
        skill ids are resolved against active SQL definitions before context is
        injected, so stale Qdrant points cannot activate removed or disabled
        skills. If the vector index is unavailable or empty, the registry falls
        back to in-memory embedding over the active SQL definitions.
        """
        if max_skills <= 0:
            return []

        query_text = self._skill_query_text(query, recent_messages=recent_messages)
        if not query_text:
            return []

        definitions = self.available_skills()
        excluded = {
            str(value).strip().lower() for value in (exclude_skill_ids or set())
        }
        excluded.update(_slugify(value) for value in excluded if value)

        if self._vector_store is not None:
            try:
                matches = self._vector_store.search(
                    query=query_text,
                    top_k=max_skills,
                    active_skill_ids=[
                        definition.skill_id for definition in definitions
                    ],
                    exclude_skill_ids=excluded,
                    min_score=min_score,
                )
            except Exception as exc:
                self.last_relevance_error = str(exc)
            else:
                by_key = self._definition_lookup(definitions)
                scored = []
                for match in matches:
                    definition = by_key.get(str(getattr(match, "skill_id", "")))
                    if definition is None:
                        definition = by_key.get(str(getattr(match, "slug", "")))
                    if definition is None:
                        continue
                    score = getattr(match, "score", None)
                    scored.append((definition, float(score or 0.0)))
                if scored:
                    self.last_relevance_error = None
                    return scored[:max_skills]

        return self._in_memory_relevant_skills(
            definitions=definitions,
            query_text=query_text,
            embedding_client=embedding_client,
            excluded=excluded,
            max_skills=max_skills,
            min_score=min_score,
        )

    def _in_memory_relevant_skills(
        self,
        *,
        definitions: list[SkillDefinition],
        query_text: str,
        embedding_client: Any | None,
        excluded: set[str],
        max_skills: int,
        min_score: float,
    ) -> list[tuple[SkillDefinition, float]]:
        """Fallback skill retrieval used when the Qdrant skill index is unavailable."""
        if embedding_client is None:
            return []
        try:
            query_vector = _embed_text(
                embedding_client,
                query_text,
                input_type="query",
            )
        except Exception as exc:
            self.last_relevance_error = str(exc)
            return []

        scored: list[tuple[SkillDefinition, float]] = []
        for definition in definitions:
            if definition.slug.lower() in excluded:
                continue
            if definition.skill_id.lower() in excluded:
                continue
            context = _bounded_text(
                self.skill_context(definition),
                max_chars=_SKILL_SEARCH_CONTEXT_CHARS,
            )
            search_text = self._skill_search_text(definition, context=context)
            if not search_text:
                continue
            try:
                skill_vector = _embed_text(
                    embedding_client,
                    search_text,
                    input_type="document",
                )
            except Exception as exc:
                self.last_relevance_error = str(exc)
                return []
            score = _cosine_similarity(query_vector, skill_vector)
            if score >= min_score:
                scored.append((definition, score))

        self.last_relevance_error = None
        scored.sort(key=lambda item: (-item[1], item[0].order, item[0].name.lower()))
        return scored[:max_skills]

    def _definition_lookup(
        self,
        definitions: list[SkillDefinition],
    ) -> dict[str, SkillDefinition]:
        """Return lookup keys used to resolve Qdrant matches back to SQL skills."""
        lookup: dict[str, SkillDefinition] = {}
        for definition in definitions:
            for key in (
                definition.skill_id,
                definition.slug,
                _slugify(definition.name),
            ):
                clean = str(key or "").strip()
                if clean:
                    lookup[clean] = definition
                    lookup[clean.lower()] = definition
        return lookup

    def _definition_for_key(self, skill_id: str | None) -> SkillDefinition | None:
        """Find an active skill by UI slug, database id, or slugified id."""
        if not skill_id:
            return None
        raw = str(skill_id).strip().lower()
        normalized = _slugify(raw)
        for definition in self.available_skills():
            if definition.slug.lower() == raw or definition.slug == normalized:
                return definition
            if definition.skill_id.lower() == raw:
                return definition
            if _slugify(definition.skill_id) == normalized:
                return definition
        return None

    def _selected_keys(
        self,
        skill_id: str | None,
        definition: SkillDefinition | None,
    ) -> set[str]:
        """Return all identifiers that should be excluded from semantic matches."""
        keys: set[str] = set()
        raw_values = [skill_id]
        if definition is not None:
            raw_values.extend([definition.skill_id, definition.slug, definition.name])
        for value in raw_values:
            clean = str(value or "").strip().lower()
            if clean:
                keys.add(clean)
                keys.add(_slugify(clean))
        return keys

    def _skill_query_text(
        self,
        query: str,
        *,
        recent_messages: Iterable[dict[str, Any]] | None = None,
    ) -> str:
        """Build the compact retrieval query from current and recent messages."""
        parts: list[str] = []
        for message in list(recent_messages or [])[-3:]:
            if not isinstance(message, dict):
                continue
            content = _string_value(message.get("content"))
            if not content:
                continue
            role = _string_value(message.get("role"), "message")
            parts.append(f"{role}: {content}")
        current = _string_value(query)
        if current:
            parts.append(f"user: {current}")
        return _bounded_text("\n".join(parts), max_chars=3_000)

    def _skill_search_text(self, definition: SkillDefinition, *, context: str) -> str:
        """Build one searchable text document for an active skill."""
        parts = [
            f"Skill name: {definition.name}",
            f"Skill slug: {definition.slug}",
            f"Source type: {definition.source_type}",
            definition.description,
            definition.instruction,
            context,
        ]
        return "\n".join(part for part in parts if str(part or "").strip()).strip()

    def _skill_context_block(
        self,
        definition: SkillDefinition,
        *,
        context: str | None = None,
        source_label: str | None = None,
    ) -> str:
        """Format one skill as a prompt-ready context block."""
        lines = [
            f"Skill: {definition.name}",
            f"Skill id: {definition.slug}",
            f"Source type: {definition.source_type}",
        ]
        if source_label:
            lines.append(f"Selection reason: {source_label}")
        if definition.description:
            lines.append(f"Description: {definition.description}")
        block_context = str(
            context if context is not None else self.skill_context(definition)
        ).strip()
        if block_context:
            lines.append("Context:\n" + block_context)
        elif definition.instruction:
            lines.append("Instruction:\n" + definition.instruction)
        return "\n".join(lines).strip()

    def _database_definitions(self) -> list[SkillDefinition] | None:
        """Load active database definitions or signal built-in fallback.

        ``None`` means the repository is missing, errored, or returned no rows, so
        the registry should use built-ins. A real list, even an empty one, means
        the database is authoritative and fallback should not add hidden skills.
        Duplicate slugs are ignored after the first active row.
        """
        if self._repository is None:
            return None
        try:
            rows = list(self._repository.list_skills(active_only=False))
        except Exception as exc:
            self.last_error = str(exc)
            return None

        self.last_error = None
        if not rows:
            return None

        definitions: list[SkillDefinition] = []
        seen: set[str] = set()
        for index, row in enumerate(rows):
            if not getattr(row, "is_active", True):
                continue
            definition = _definition_from_row(row, fallback_order=1000 + index)
            if definition.slug in seen:
                continue
            if definition.handler or definition.instruction:
                definitions.append(definition)
                seen.add(definition.slug)
        return sorted(definitions, key=lambda item: (item.order, item.name.lower()))

    def _execute_handler(
        self,
        handler: str,
        *,
        shift_date: date,
        shift_label: str,
    ) -> str:
        """Call a supported ``SkillEngine`` method for code-backed skills.

        The method uses explicit branches instead of dynamic ``getattr`` so a DB
        row cannot call arbitrary engine attributes. Add new branches here only
        when a new code-backed skill is intentionally supported.
        """
        if handler == "optimise_prompt":
            return str(self._engine.optimise_prompt())
        if handler == "shift_to_best_prompt":
            return str(self._engine.shift_to_best_prompt(str(shift_date), shift_label))
        if handler == "heatload_prompt":
            return str(self._engine.heatload_prompt())
        if handler == "shift_report_prompt":
            start_utc, end_utc = self._shift_window_utc(shift_date, shift_label)
            return str(
                self._engine.shift_report_prompt(
                    str(shift_date),
                    shift_label,
                    start_utc,
                    end_utc,
                )
            )
        raise ValueError(f"Unsupported FurnaceMind skill handler: {handler}")

    def _prompt_from_instruction(
        self,
        definition: SkillDefinition,
        *,
        shift_date: date,
        shift_label: str,
    ) -> str:
        """Build a prompt for database skills without a code-backed handler.

        Prompt-only skills can provide a ``prompt_template`` in metadata or rely
        on the main instruction text. This keeps custom skills database-driven
        while still giving them the same click-to-chat behavior as built-ins.
        """
        template = _string_value(definition.metadata.get("prompt_template"))
        if template:
            return _format_template(
                template,
                shift_date=shift_date,
                shift_label=shift_label,
            )
        if definition.instruction:
            return f"SKILL: {definition.name}\n{definition.instruction}"
        return f"SKILL: {definition.name}\nUse the active skill context to respond."

    @staticmethod
    def _shift_window_utc(shift_date: date, shift_label: str) -> tuple[str, str]:
        """Return UTC ISO bounds needed by the shift-report engine handler.

        The UI works with local shift dates/labels, while the underlying report
        prompt expects explicit UTC timestamps. The import stays local to avoid a
        broader dependency at module import time.
        """
        from utils.shift_windows import shift_window

        start_local, end_local = shift_window(shift_date, shift_label)
        start_utc = start_local.astimezone(timezone.utc).isoformat()
        end_utc = end_local.astimezone(timezone.utc).isoformat()
        return start_utc, end_utc
