METRIC_MAP:
  "ETA CO": "FurnaceTopGasAnalysisCO2ETACO"
  "Total Fuel": "Act. Fuel RateKg/Thm."

MEASUREMENT_LABELS:
  heatload_delta_t: "Heatload Delta T"
  process_params: "Process Params"
  temperature_profile: "Temperature Profile"

FREQUENCY_TO_TIMEDTA:
  "None": null
  "1 minute": "1min"
  "5 minutes": "5min"
  "10 minutes": "10min"
  "15 minutes": "15min"
  "30 minutes": "30min"
  "1 hour": "1h"
  "6 hours": "6h"
  "8 hours": "8h"
  "12 hours": "12h"
  "1 day": "1d"