hoppers:
  - HOPPER 01
  - HOPPER 02
  - HOPPER 03
  - HOPPER 04
  - HOPPER 05
  - HOPPER 06
  - HOPPER 07
  - HOPPER 08
  - HOPPER 09
  - HOPPER 10
  - HOPPER 11
  - HOPPER 12
  - HOPPER 13
  - HOPPER 14
  - HOPPER 15
  - HOPPER 16
  - HOPPER 17
  - HOPPER 18
  - HOPPER 19

materials:
  - Coke Online
  - Sinter
  - Bacheli oversize CLO
  - Lloyds CLO
  - Geomin CLO
  - Quartz
  - Coke Offline
  - Nut Coke
  - Lloyds Pellet
  - Lime Stone
  - Dolomite
  - Sarda Energy & Minerals Limited
  - NMDC Limited Lumps (10-150 MM) (Kirandul)
  - SS Enterprises- High Manetite
  - ACORE INDUSTRIES PRIVATE LIMITED (MANGANESE ORE LUMP)
  - TIRUPATI MINERALS & METALS (MANGANESE ORE LUMP)
  - NMDC Limited (Donimalai)
  - NMDC Limited (Kumarswamy)
  - JAYASWAL NECO INDUSTRIES LIMITED
  - Geomin (60%) Iron Fines Oversize (+10MM)
  - Lloyds Metals Iron Fines Oversize (+10MM)
  - NMDC Limited (Donimalai) Iron Fines Oversize (+10MM)
  - NMDC Limited (Bachelli) Iron Fines Oversize (+10MM)
  - Geomin Iron Manufacturing Fines Oversize (+40MM)
  - Geomin Fines Oversize(+40MM)
  - NMDC CLO Oversize (+40MM) (Donimalai)
  - Lloyds Metals & EnergyCLO Oversize (+40MM)
  - NMDC Limited Crushed ROM (10-40MM) (Kirandul)
  - Geomin Fines Oversize(+10MM)
  - NMDC CLO Oversize (+10MM) (Donimalai)
  - Lloyds Metals CLO Oversize (+10MM)



burden_fields:
  - "COKE P01 RINGS"
  - "COKE P02 RINGS"
  - "COKE P03 RINGS"
  - "COKE P04 RINGS"
  - "COKE P05 RINGS"
  - "COKE P06 RINGS"
  - "COKE P07 RINGS"
  - "COKE P08 RINGS"
  - "COKE P09 RINGS"
  - "COKE P10 RINGS"
  - "COKE P11 RINGS"

  - "COKE P01 ANGLES"
  - "COKE P02 ANGLES"
  - "COKE P03 ANGLES"
  - "COKE P04 ANGLES"
  - "COKE P05 ANGLES"
  - "COKE P06 ANGLES"
  - "COKE P07 ANGLES"
  - "COKE P08 ANGLES"
  - "COKE P09 ANGLES"
  - "COKE P10 ANGLES"
  - "COKE P11 ANGLES"

  - "COKE_DISCHARGE_TIME"
  - "COKE_CHARGE_PATTERN"

  - "NONCOKE P01 RINGS"
  - "NONCOKE P02 RINGS"
  - "NONCOKE P03 RINGS"
  - "NONCOKE P04 RINGS"
  - "NONCOKE P05 RINGS"
  - "NONCOKE P06 RINGS"
  - "NONCOKE P07 RINGS"
  - "NONCOKE P08 RINGS"
  - "NONCOKE P09 RINGS"
  - "NONCOKE P10 RINGS"
  - "NONCOKE P11 RINGS"

  - "NONCOKE P01 ANGLES"
  - "NONCOKE P02 ANGLES"
  - "NONCOKE P03 ANGLES"
  - "NONCOKE P04 ANGLES"
  - "NONCOKE P05 ANGLES"
  - "NONCOKE P06 ANGLES"
  - "NONCOKE P07 ANGLES"
  - "NONCOKE P08 ANGLES"
  - "NONCOKE P09 ANGLES"
  - "NONCOKE P10 ANGLES"
  - "NONCOKE P11 ANGLES"

  - "NON_COKE_DISCHARGE_TIME"
  - "NON_COKE_CHARGE_PATTERN"
  - "BURDEN_CHANGING_PURPOSE"