DATA: data/data.pkl
IMG_HOSPET: images/HOSPET.jpeg
IMG_MBF: images/MBF.jpg
IMG_VOPTIMAI: images/VOPTIMAI.png
LAMBDA_REG: 0.05
OPTIM_STEPS: 30
Optimisation:
  Eta CO:
    control_params:
    - Hot Blast VolumeNm3/Hr.
    - Hot Blast PressureBar
    - TopPressureBar
    - Hot Blast Temp.oC
    - SteamKgs/Hr.
    - PermeabilityKgs/Hr.
    - O2 Enrichment %
    - Total OxygenNm3/Hr.
    - TuyereVelocitym/s
    - ActualKg/Thm.
    input_params:
      Coke:
      - COKE_VM%
      - COKE_ASH%
      - COKE_IM%
      - COKE_FC%
      - COKE_MOIST%
      Flux:
      - FLUX_TM%
      - FLUX_SiO2%
      - FLUX_Fe2O3%
      - FLUX_Al2O3%
      - FLUX_LOI%
      - FLUX_MgO%
      - FLUX_CaO%
      - FLUX_MT
      NutCoke:
      - NUTCOKE_MOIST%
      - NUTCOKE_Prime_MT
      - NUTCOKE_VM%
      - NUTCOKE_IM%
      - NUTCOKE_FC%
      - NUTCOKE_ASH%
      Ore:
      - Geomin Type
      - ORE_%Fe(T)
      - ORE_%LOI
      - ORE_%TM
      - ORE_%MgO
      - ORE_%Na2O
      - ORE_%P
      - ORE_%TiO2
      - ORE_%Al2O3
      - ORE_%SiO2
      - ORE_%MnO
      - ORE_%CaO
      - ORE_%K2O
      PCI:
      - PCI_2_%FC
      - PCI_2_%Ash
      - PCI_2_%VM
      - PCI_2_%IM
      - PCI_2_%TM
      Sinter:
      - Sinter_SP_02_Hot_strength_RDI
      - Sinter_SP_02_Cold_Strength_AI
      - Sinter_SP_02_Cold_strength_TI
      - Sinter_SP_02_P%
      - Sinter_SP_02_SiO2%
      - Sinter_SP_02_MgO%
      - Sinter_SP_02_FeO%
      - Sinter_SP_02_Al2O3%
      - Sinter_SP_02_Na2O%
      - Sinter_SP_02_TiO2%
      - Sinter_SP_02_Fe(T)%
      - Sinter_SP_02_CaO%
      - Sinter_SP_02_K2O%
      - Sinter_SP_02_Basicity
      - Sinter_SP_02_MnO%
    maxmin: -1.0
    model: src/models/eta_co_opt.pkl
    output_param: FurnaceTopGasAnalysisCO2ETACO
    scaling: src/models/eta_co_scaler.pkl
  Production Rate:
    control_params:
    - Hot Blast VolumeNm3/Hr.
    - Hot Blast PressureBar
    - TopPressureBar
    - Hot Blast Temp.oC
    - SteamKgs/Hr.
    - PermeabilityKgs/Hr.
    - O2 Enrichment %
    - Total OxygenNm3/Hr.
    - TuyereVelocitym/s
    - ActualKg/Thm.
    input_params:
      Coke:
      - COKE_VM%
      - COKE_ASH%
      - COKE_IM%
      - COKE_FC%
      - COKE_MOIST%
      Flux:
      - FLUX_TM%
      - FLUX_SiO2%
      - FLUX_Fe2O3%
      - FLUX_Al2O3%
      - FLUX_LOI%
      - FLUX_MgO%
      - FLUX_CaO%
      - FLUX_MT
      NutCoke:
      - NUTCOKE_MOIST%
      - NUTCOKE_Prime_MT
      - NUTCOKE_VM%
      - NUTCOKE_IM%
      - NUTCOKE_FC%
      - NUTCOKE_ASH%
      Ore:
      - Geomin Type
      - ORE_%Fe(T)
      - ORE_%LOI
      - ORE_%TM
      - ORE_%MgO
      - ORE_%Na2O
      - ORE_%P
      - ORE_%TiO2
      - ORE_%Al2O3
      - ORE_%SiO2
      - ORE_%MnO
      - ORE_%CaO
      - ORE_%K2O
      PCI:
      - PCI_2_%FC
      - PCI_2_%Ash
      - PCI_2_%VM
      - PCI_2_%IM
      - PCI_2_%TM
      Sinter:
      - Sinter_SP_02_Hot_strength_RDI
      - Sinter_SP_02_Cold_Strength_AI
      - Sinter_SP_02_Cold_strength_TI
      - Sinter_SP_02_P%
      - Sinter_SP_02_SiO2%
      - Sinter_SP_02_MgO%
      - Sinter_SP_02_FeO%
      - Sinter_SP_02_Al2O3%
      - Sinter_SP_02_Na2O%
      - Sinter_SP_02_TiO2%
      - Sinter_SP_02_Fe(T)%
      - Sinter_SP_02_CaO%
      - Sinter_SP_02_K2O%
      - Sinter_SP_02_Basicity
      - Sinter_SP_02_MnO%
    maxmin: 1.0
    model: src/models/prod_rate_opt.pkl
    output_param: ProductionTonnesPerHr
    scaling: src/models/prod_rate_scaler.pkl
  UnitCost:
    control_params:
    - Hot Blast VolumeNm3/Hr.
    - Hot Blast PressureBar
    - TopPressureBar
    - Hot Blast Temp.oC
    - SteamKgs/Hr.
    - PermeabilityKgs/Hr.
    - O2 Enrichment %
    input_params:
      Coke:
      - COKE_VM%
      - COKE_ASH%
      - COKE_IM%
      - COKE_FC%
      - COKE_MOIST%
      Flux:
      - FLUX_TM%
      - FLUX_SiO2%
      - FLUX_Fe2O3%
      - FLUX_Al2O3%
      - FLUX_LOI%
      - FLUX_MgO%
      - FLUX_CaO%
      - FLUX_MT
      NutCoke:
      - NUTCOKE_MOIST%
      - NUTCOKE_Prime_MT
      - NUTCOKE_VM%
      - NUTCOKE_IM%
      - NUTCOKE_FC%
      - NUTCOKE_ASH%
      Ore:
      - Geomin Type
      - ORE_%Fe(T)
      - ORE_%LOI
      - ORE_%TM
      - ORE_%MgO
      - ORE_%Na2O
      - ORE_%P
      - ORE_%TiO2
      - ORE_%Al2O3
      - ORE_%SiO2
      - ORE_%MnO
      - ORE_%CaO
      - ORE_%K2O
      PCI:
      - PCI_2_%FC
      - PCI_2_%Ash
      - PCI_2_%VM
      - PCI_2_%IM
      - PCI_2_%TM
      Sinter:
      - Sinter_SP_02_Hot_strength_RDI
      - Sinter_SP_02_Cold_Strength_AI
      - Sinter_SP_02_Cold_strength_TI
      - Sinter_SP_02_P%
      - Sinter_SP_02_SiO2%
      - Sinter_SP_02_MgO%
      - Sinter_SP_02_FeO%
      - Sinter_SP_02_Al2O3%
      - Sinter_SP_02_Na2O%
      - Sinter_SP_02_TiO2%
      - Sinter_SP_02_Fe(T)%
      - Sinter_SP_02_CaO%
      - Sinter_SP_02_K2O%
      - Sinter_SP_02_Basicity
      - Sinter_SP_02_MnO%
    maxmin: -1.0
    model: src/models/unitcost_opt2.pkl
    output_param: UnitCost 1000Rs/Thm
    scaling: src/models/unitcost_scaler2.pkl
TIMESTEPS: 3
field_mapping:
  Geomin Type: Geomin Type
  coke_ash_pct: COKE_ASH%
  coke_fc_pct: COKE_FC%
  coke_im_pct: COKE_IM%
  coke_moist_pct: COKE_MOIST%
  coke_mt: COKE_MT
  coke_vm_pct: COKE_VM%
  flux_al2o3_pct: FLUX_Al2O3%
  flux_cao_pct: FLUX_CaO%
  flux_fe2o3_pct: FLUX_Fe2O3%
  flux_loi_pct: FLUX_LOI%
  flux_mgo_pct: FLUX_MgO%
  flux_mt: FLUX_MT
  flux_sio2_pct: FLUX_SiO2%
  flux_tm_pct: FLUX_TM%
  nutcoke_ash_pct: NUTCOKE_ASH%
  nutcoke_fc_pct: NUTCOKE_FC%
  nutcoke_im_pct: NUTCOKE_IM%
  nutcoke_moist_pct: NUTCOKE_MOIST%
  nutcoke_prime_mt: NUTCOKE_Prime_MT
  nutcoke_vm_pct: NUTCOKE_VM%
  ore_al2o3_pct: ORE_%Al2O3
  ore_cao_pct: ORE_%CaO
  ore_fe_total_pct: ORE_%Fe(T)
  ore_k2o_pct: ORE_%K2O
  ore_loi_pct: ORE_%LOI
  ore_mgo_pct: ORE_%MgO
  ore_mno_pct: ORE_%MnO
  ore_mt: ORE_MT
  ore_na2o_pct: ORE_%Na2O
  ore_p_pct: ORE_%P
  ore_sio2_pct: ORE_%SiO2
  ore_tio2_pct: ORE_%TiO2
  ore_tm_pct: ORE_%TM
  pci2_ash_pct: PCI_2_%Ash
  pci2_fc_pct: PCI_2_%FC
  pci2_im_pct: PCI_2_%IM
  pci2_tm_pct: PCI_2_%TM
  pci2_vm_pct: PCI_2_%VM
  sinter_al2o3_pct: Sinter_SP_02_Al2O3%
  sinter_cao_pct: Sinter_SP_02_CaO%
  sinter_cold_strength_ai: Sinter_SP_02_Cold_Strength_AI
  sinter_cold_strength_ti: Sinter_SP_02_Cold_strength_TI
  sinter_fe_total_pct: Sinter_SP_02_Fe(T)%
  sinter_feo_pct: Sinter_SP_02_FeO%
  sinter_hot_strength_rdi: Sinter_SP_02_Hot_strength_RDI
  sinter_k2o_pct: Sinter_SP_02_K2O%
  sinter_mgo_pct: Sinter_SP_02_MgO%
  sinter_mno_pct: Sinter_SP_02_MnO%
  sinter_na2o_pct: Sinter_SP_02_Na2O%
  sinter_p_pct: Sinter_SP_02_P%
  sinter_sio2_pct: Sinter_SP_02_SiO2%
  sinter_sp_02_basicity: Sinter_SP_02_Basicity
  sinter_tio2_pct: Sinter_SP_02_TiO2%
influxdb_ml_database:
  database: ML DATASET
  measurements: rm_charge_data
  time_range: last 1 month
