DATA: data/data.pkl
IMG_HOSPET: images/HOSPET.jpeg
IMG_MBF: images/MBF.jpg
IMG_VOPTIMAI: images/VOPTIMAI.png
LAMBDA_REG: 0.05
OPTIM_STEPS: 30
Optimisation:
  Eta CO:
    output_param: FURNACETOPGASANALYSISCO2ETACO
    model: src/models/etaco_model.pkl
    scaling: src/models/etaco_scaler.pkl
    maxmin: -1.0
    control_params:
    - HOT BLAST PRESSUREBAR
    - TOPPRESSUREBAR
    - HOT BLAST TEMP.OC
    - STEAMKGS/HR.
    - HOT BLAST VOLUMENM3/HR.
    - O2 ENRICHMENT %
    input_params:
      Coke:
      - COKE_ASH%
      - COKE_FC%
      - COKE_IM%
      - COKE_MOIST%
      - COKE_VM%
      - COKE_CALC_MT
      - COKE_DISCHARGE_TIME
      NutCoke:
      - NUTCOKE_ASH%
      - NUTCOKE_FC%
      - NUTCOKE_IM%
      - NUTCOKE_MOIST%
      - NUTCOKE_VM%
      - NUTCOKE_CALC_MT
      PCI:
      - PCI_2_ASH%
      - PCI_2_FC%
      - PCI_2_IM%
      - PCI_2_VM%
      - PCI_2_CALC_MT
      Ore:
      - ORE_AL2O3%
      - ORE_CAO%
      - ORE_FE(T)%
      - ORE_K2O%
      - ORE_LOI%
      - ORE_MGO%
      - ORE_MNO%
      - ORE_CALC_MT
      - ORE_NA2O%
      - ORE_P%
      - ORE_SIO2%
      - ORE_TIO2%
      - ORE_TM%
      Sinter:
      - SINTER_SP_02_AL2O3%
      - SINTER_SP_02_CAO%
      - SINTER_SP_02_COLD_STRENGTH_AI
      - SINTER_SP_02_COLD_STRENGTH_TI
      - SINTER_SP_02_FE(T)%
      - SINTER_SP_02_FEO%
      - SINTER_SP_02_HOT_STRENGTH_RDI
      - SINTER_SP_02_HOT_STRENGTH_RI
      - SINTER_SP_02_K2O%
      - SINTER_SP_02_MGO%
      - SINTER_SP_02_MNO%
      - SINTER_CALC_MT
      - SINTER_SP_02_NA2O%
      - SINTER_SP_02_P%
      - SINTER_SP_02_SIO2%
      - SINTER_SP_02_BASICITY
      - SINTER_SP_02_TIO2%
      Pellet:
      - LLOYDS_PELLET_PCT_CAO
      - TOTAL_PELLET_CALC_MT
      - LLOYDS_PELLET_PCT_AL2O3
      - LLOYDS_PELLET_PCT_FE2O3
      - LLOYDS_PELLET_PCT_K2O
      - LLOYDS_PELLET_PCT_LOI
      - LLOYDS_PELLET_PCT_MGO
      - LLOYDS_PELLET_PCT_MNO
      - LLOYDS_PELLET_PCT_NA2O
      - LLOYDS_PELLET_PCT_P
      - LLOYDS_PELLET_PCT_SIO2
      - LLOYDS_PELLET_PCT_TIO2
      - LLOYDS_PELLET_PCT_TM
      Flux:
      - FLUX_AL2O3%
      - FLUX_CAO%
      - FLUX_FE2O3%
      - FLUX_LOI%
      - FLUX_MGO%
      - FLUX_CALC_MT
      - FLUX_SIO2%
      - FLUX_TM%
      Burden:
      - WEIGHTED_COKE_ANGLE
      - WEIGHTED_NON_COKE_ANGLE
      - TOTAL_COKE_PORTIONS
      - TOTAL_NON_COKE_PORTIONS
      - NON_COKE_DISCHARGE_TIME
      Temperature:
      - BELLY - 15162_TEMP. OCAT-07DEG. OC
      - BELLY - 15162_TEMP. OC.2CT-17DEG. OC
      - BELLY - 15162_TEMP. OC.3DT-03DEG. OC
      - BOSH - 12975_TEMP. OCAT-07DEG. OC
      - BOSH - 12975_TEMP. OC.1BT-12DEG. OC
      - BOSH - 12975_TEMP. OC.2CT-17DEG. OC
      - BOSH - 12975_TEMP. OC.3DT-03DEG. OC
      - LOWER STACK - 18660_TEMP. OCAT-07DEG. OC
      - LOWER STACK - 18660_TEMP. OC.1BT-12DEG. OC
      - LOWER STACK - 18660_TEMP. OC.2CT-17DEG. OC
      - LOWER STACK - 18660_TEMP. OC.3DT-03DEG. OC
      - FURNACE TOP GAS_UPTAKE TEMP. OC.4AVG.DEG. OC
      - FURNACE TOP GAS_UPTAKE TEMP. OC.1BT-12DEG. OC
      - FURNACE TOP GAS_UPTAKE TEMP. OCAT-16DEG. OC
      - FURNACE TOP GAS_UPTAKE TEMP. OC.2CT-08DEG. OC
      - FURNACE TOP GAS_UPTAKE TEMP. OC.3DT-04DEG. OC
      - HEARTH PAD CENTER_TEMP. OCA4.3 MTR.DEG. OC
      - HEARTH PAD CENTER_TEMP. OC.1B5.4 MTR.DEG. OC
      - HEARTH PAD CENTER_TEMP. OC.2C5.7 MTR.DEG. OC
      - HEARTH PAD CENTER_TEMP. OC.3D6.1 MTR.DEG. OC
      Other:
      - FURNACE TOP GAS ANALYSISH2%
  Production Rate:
    output_param: PRODUCTIONTONNESPERHR
    model: src/models/productionrate_model.pkl
    scaling: src/models/productionrate_scaler.pkl
    maxmin: -1.0
    control_params:
    - HOT BLAST PRESSUREBAR
    - TOPPRESSUREBAR
    - HOT BLAST TEMP.OC
    - STEAMKGS/HR.
    - HOT BLAST VOLUMENM3/HR.
    - ACTUALKG/THM.
    - O2 ENRICHMENT %
    input_params:
      Coke:
      - COKE_ASH%
      - COKE_FC%
      - COKE_IM%
      - COKE_MOIST%
      - COKE_VM%
      - COKE_CALC_MT
      - COKE_DISCHARGE_TIME
      NutCoke:
      - NUTCOKE_ASH%
      - NUTCOKE_FC%
      - NUTCOKE_IM%
      - NUTCOKE_MOIST%
      - NUTCOKE_VM%
      - NUTCOKE_CALC_MT
      PCI:
      - PCI_2_ASH%
      - PCI_2_FC%
      - PCI_2_IM%
      - PCI_2_VM%
      - PCI_2_CALC_MT
      Ore:
      - ORE_AL2O3%
      - ORE_CAO%
      - ORE_FE(T)%
      - ORE_K2O%
      - ORE_LOI%
      - ORE_MGO%
      - ORE_MNO%
      - ORE_CALC_MT
      - ORE_NA2O%
      - ORE_P%
      - ORE_SIO2%
      - ORE_TIO2%
      - ORE_TM%
      Sinter:
      - SINTER_SP_02_AL2O3%
      - SINTER_SP_02_CAO%
      - SINTER_SP_02_COLD_STRENGTH_AI
      - SINTER_SP_02_COLD_STRENGTH_TI
      - SINTER_SP_02_FE(T)%
      - SINTER_SP_02_FEO%
      - SINTER_SP_02_HOT_STRENGTH_RDI
      - SINTER_SP_02_HOT_STRENGTH_RI
      - SINTER_SP_02_K2O%
      - SINTER_SP_02_MGO%
      - SINTER_SP_02_MNO%
      - SINTER_CALC_MT
      - SINTER_SP_02_NA2O%
      - SINTER_SP_02_P%
      - SINTER_SP_02_SIO2%
      - SINTER_SP_02_BASICITY
      - SINTER_SP_02_TIO2%
      Pellet:
      - LLOYDS_PELLET_PCT_CAO
      - TOTAL_PELLET_CALC_MT
      - LLOYDS_PELLET_PCT_AL2O3
      - LLOYDS_PELLET_PCT_FE2O3
      - LLOYDS_PELLET_PCT_K2O
      - LLOYDS_PELLET_PCT_LOI
      - LLOYDS_PELLET_PCT_MGO
      - LLOYDS_PELLET_PCT_MNO
      - LLOYDS_PELLET_PCT_NA2O
      - LLOYDS_PELLET_PCT_P
      - LLOYDS_PELLET_PCT_SIO2
      - LLOYDS_PELLET_PCT_TIO2
      - LLOYDS_PELLET_PCT_TM
      Flux:
      - FLUX_AL2O3%
      - FLUX_CAO%
      - FLUX_FE2O3%
      - FLUX_LOI%
      - FLUX_MGO%
      - FLUX_CALC_MT
      - FLUX_SIO2%
      - FLUX_TM%
      Burden:
      - WEIGHTED_COKE_ANGLE
      - WEIGHTED_NON_COKE_ANGLE
      - TOTAL_COKE_PORTIONS
      - TOTAL_NON_COKE_PORTIONS
      - NON_COKE_DISCHARGE_TIME
      Other:
      - FURNACE TOP GAS ANALYSISH2%
      - CHARGES/HRS.
      - STOCKRODLEVEL
  UnitCost:
    control_params:
    - HOT BLAST PRESSUREBAR
    - TOPPRESSUREBAR
    - HOT BLAST TEMP.OC
    - STEAMKGS/HR.
    - HOT BLAST VOLUMENM3/HR.
    - O2 ENRICHMENT %
    input_params:
      Coke:
      - COKE_VM%
      - COKE_ASH%
      - COKE_IM%
      - COKE_FC%
      - COKE_MOIST%
      - COKE_CALC_MT
      NutCoke:
      - NUTCOKE_MOIST%
      - NUTCOKE_CALC_MT
      - NUTCOKE_VM%
      - NUTCOKE_IM%
      - NUTCOKE_FC%
      - NUTCOKE_ASH%
      PCI:
      - PCI_2_FC%
      - PCI_2_ASH%
      - PCI_2_VM%
      - PCI_2_IM%
      - PCI_2_CALC_MT
      Ore:
      - GEOMIN TYPE
      - ORE_FE(T)%
      - ORE_LOI%
      - ORE_TM%
      - ORE_MGO%
      - ORE_NA2O%
      - ORE_P%
      - ORE_TIO2%
      - ORE_AL2O3%
      - ORE_SIO2%
      - ORE_MNO%
      - ORE_CAO%
      - ORE_K2O%
      - ORE_CALC_MT
      Sinter:
      - SINTER_SP_02_HOT_STRENGTH_RI
      - SINTER_SP_02_HOT_STRENGTH_RDI
      - SINTER_SP_02_COLD_STRENGTH_AI
      - SINTER_SP_02_COLD_STRENGTH_TI
      - SINTER_SP_02_P%
      - SINTER_SP_02_SIO2%
      - SINTER_SP_02_MGO%
      - SINTER_SP_02_FEO%
      - SINTER_SP_02_AL2O3%
      - SINTER_SP_02_NA2O%
      - SINTER_SP_02_TIO2%
      - SINTER_SP_02_FE(T)%
      - SINTER_SP_02_CAO%
      - SINTER_SP_02_K2O%
      - SINTER_SP_02_BASICITY
      - SINTER_SP_02_MNO%
      - SINTER_CALC_MT
      Pellet:
      - LLOYDS_PELLET_PCT_SIO2
      - LLOYDS_PELLET_PCT_AL2O3
      - LLOYDS_PELLET_PCT_FE2O3
      - LLOYDS_PELLET_PCT_MGO
      - LLOYDS_PELLET_PCT_TIO2
      - LLOYDS_PELLET_PCT_NA2O
      - TOTAL_PELLET_CALC_MT
      - LLOYDS_PELLET_PCT_K2O
      - LLOYDS_PELLET_PCT_TM
      - LLOYDS_PELLET_PCT_LOI
      - LLOYDS_PELLET_PCT_MNO
      - LLOYDS_PELLET_PCT_CAO
      - LLOYDS_PELLET_PCT_P
      Flux:
      - FLUX_TM%
      - FLUX_SIO2%
      - FLUX_FE2O3%
      - FLUX_AL2O3%
      - FLUX_LOI%
      - FLUX_MGO%
      - FLUX_CAO%
      - FLUX_CALC_MT
      Burden:
      - COKE_DISCHARGE_TIME
      - WEIGHTED_COKE_ANGLE
      - TOTAL_COKE_PORTIONS
      - NON_COKE_DISCHARGE_TIME
      - WEIGHTED_NON_COKE_ANGLE
      - TOTAL_NON_COKE_PORTIONS
      Other:
      - CHARGES/HRS.
      - STOCKRODLEVEL
      - FURNACE TOP GAS ANALYSISH2%
    maxmin: 1.0
    model: src/models/unitcost_model.pkl
    output_param: UNITCOST LAKHS/THM
    scaling: src/models/unitcost_scaler.pkl
  Fuel Rate:
    control_params:
    - HOT BLAST PRESSUREBAR
    - TOPPRESSUREBAR
    - HOT BLAST TEMP.OC
    - STEAMKGS/HR.
    - HOT BLAST VOLUMENM3/HR.
    - O2 ENRICHMENT %
    input_params:
      Coke:
      - COKE_VM%
      - COKE_ASH%
      - COKE_IM%
      - COKE_FC%
      - COKE_MOIST%
      - COKE_CALC_MT
      NutCoke:
      - NUTCOKE_MOIST%
      - NUTCOKE_CALC_MT
      - NUTCOKE_VM%
      - NUTCOKE_IM%
      - NUTCOKE_FC%
      - NUTCOKE_ASH%
      PCI:
      - PCI_2_FC%
      - PCI_2_ASH%
      - PCI_2_VM%
      - PCI_2_IM%
      Ore:
      - ORE_FE(T)%
      - ORE_LOI%
      - ORE_TM%
      - ORE_MGO%
      - ORE_NA2O%
      - ORE_P%
      - ORE_TIO2%
      - ORE_AL2O3%
      - ORE_SIO2%
      - ORE_MNO%
      - ORE_CAO%
      - ORE_K2O%
      - ORE_CALC_MT
      Sinter:
      - SINTER_SP_02_HOT_STRENGTH_RI
      - SINTER_SP_02_HOT_STRENGTH_RDI
      - SINTER_SP_02_COLD_STRENGTH_AI
      - SINTER_SP_02_COLD_STRENGTH_TI
      - SINTER_SP_02_P%
      - SINTER_SP_02_SIO2%
      - SINTER_SP_02_MGO%
      - SINTER_SP_02_FEO%
      - SINTER_SP_02_AL2O3%
      - SINTER_SP_02_NA2O%
      - SINTER_SP_02_TIO2%
      - SINTER_SP_02_FE(T)%
      - SINTER_SP_02_CAO%
      - SINTER_SP_02_K2O%
      - SINTER_SP_02_BASICITY
      - SINTER_SP_02_MNO%
      - SINTER_CALC_MT
      Pellet:
      - LLOYDS_PELLET_PCT_SIO2
      - LLOYDS_PELLET_PCT_AL2O3
      - LLOYDS_PELLET_PCT_FE2O3
      - LLOYDS_PELLET_PCT_MGO
      - LLOYDS_PELLET_PCT_TIO2
      - LLOYDS_PELLET_PCT_NA2O
      - TOTAL_PELLET_CALC_MT
      - LLOYDS_PELLET_PCT_K2O
      - LLOYDS_PELLET_PCT_TM
      - LLOYDS_PELLET_PCT_LOI
      - LLOYDS_PELLET_PCT_MNO
      - LLOYDS_PELLET_PCT_CAO
      - LLOYDS_PELLET_PCT_P
      Flux:
      - FLUX_TM%
      - FLUX_SIO2%
      - FLUX_FE2O3%
      - FLUX_AL2O3%
      - FLUX_LOI%
      - FLUX_MGO%
      - FLUX_CAO%
      - FLUX_CALC_MT
    maxmin: 1.0
    model: src/models/fuelrate_model.pkl
    output_param: ACT. FUEL RATEKG/THM.
    scaling: src/models/fuelrate_scaler.pkl
  Coke Rate:
    output_param: COKE RATE KG/THM
    model: src/models/cokerate_model.pkl
    scaling: src/models/cokerate_scaler.pkl
    maxmin: 1.0
    control_params:
    - HOT BLAST PRESSUREBAR
    - TOPPRESSUREBAR
    - HOT BLAST TEMP.OC
    - STEAMKGS/HR.
    - HOT BLAST VOLUMENM3/HR.
    - O2 ENRICHMENT %
    input_params:
      Coke:
      - COKE_ASH%
      - COKE_FC%
      - COKE_IM%
      - COKE_MOIST%
      - COKE_VM%
      - COKE_CALC_MT
      NutCoke:
      - NUTCOKE_ASH%
      - NUTCOKE_FC%
      - NUTCOKE_IM%
      - NUTCOKE_MOIST%
      - NUTCOKE_VM%
      - NUTCOKE_CALC_MT
      PCI:
      - PCI_2_ASH%
      - PCI_2_FC%
      - PCI_2_IM%
      - PCI_2_VM%
      Ore:
      - ORE_AL2O3%
      - ORE_CAO%
      - ORE_FE(T)%
      - ORE_K2O%
      - ORE_LOI%
      - ORE_MGO%
      - ORE_MNO%
      - ORE_CALC_MT
      - ORE_NA2O%
      - ORE_P%
      - ORE_SIO2%
      - ORE_TIO2%
      - ORE_TM%
      Sinter:
      - SINTER_SP_02_CAO%
      - SINTER_SP_02_COLD_STRENGTH_AI
      - SINTER_SP_02_COLD_STRENGTH_TI
      - SINTER_SP_02_FE(T)%
      - SINTER_SP_02_FEO%
      - SINTER_SP_02_HOT_STRENGTH_RDI
      - SINTER_SP_02_HOT_STRENGTH_RI
      - SINTER_SP_02_K2O%
      - SINTER_SP_02_MGO%
      - SINTER_SP_02_MNO%
      - SINTER_CALC_MT
      - SINTER_SP_02_NA2O%
      - SINTER_SP_02_P%
      - SINTER_SP_02_SIO2%
      - SINTER_SP_02_BASICITY
      - SINTER_SP_02_TIO2%
      Pellet:
      - LLOYDS_PELLET_PCT_CAO
      - TOTAL_PELLET_CALC_MT
      - LLOYDS_PELLET_PCT_AL2O3
      - LLOYDS_PELLET_PCT_FE2O3
      - LLOYDS_PELLET_PCT_K2O
      - LLOYDS_PELLET_PCT_LOI
      - LLOYDS_PELLET_PCT_MGO
      - LLOYDS_PELLET_PCT_MNO
      - LLOYDS_PELLET_PCT_NA2O
      - LLOYDS_PELLET_PCT_P
      - LLOYDS_PELLET_PCT_SIO2
      - LLOYDS_PELLET_PCT_TIO2
      - LLOYDS_PELLET_PCT_TM
      Flux:
      - FLUX_AL2O3%
      - FLUX_CAO%
      - FLUX_FE2O3%
      - FLUX_LOI%
      - FLUX_MGO%
      - FLUX_CALC_MT
      - FLUX_SIO2%
      - FLUX_TM%
TIMESTEPS: 3
field_mapping:
  Sinter_SP_02_Basicity: SINTER_SP_02_BASICITY
  coke_ash_pct: COKE_ASH%
  coke_fc_pct: COKE_FC%
  coke_im_pct: COKE_IM%
  coke_moist_pct: COKE_MOIST%
  coke_vm_pct: COKE_VM%
  coke_mt: COKE_CALC_MT
  flux_al2o3_pct: FLUX_AL2O3%
  flux_cao_pct: FLUX_CAO%
  flux_fe2o3_pct: FLUX_FE2O3%
  flux_loi_pct: FLUX_LOI%
  flux_mgo_pct: FLUX_MGO%
  flux_mt: FLUX_CALC_MT
  flux_sio2_pct: FLUX_SIO2%
  flux_tm_pct: FLUX_TM%
  GeominType: GEOMIN TYPE
  nutcoke_ash_pct: NUTCOKE_ASH%
  nutcoke_fc_pct: NUTCOKE_FC%
  nutcoke_im_pct: NUTCOKE_IM%
  nutcoke_moist_pct: NUTCOKE_MOIST%
  nutcoke_prime_mt: NUTCOKE_CALC_MT
  nutcoke_vm_pct: NUTCOKE_VM%
  ore_al2o3_pct: ORE_AL2O3%
  ore_cao_pct: ORE_CAO%
  ore_fe_total_pct: ORE_FE(T)%
  ore_k2o_pct: ORE_K2O%
  ore_loi_pct: ORE_LOI%
  ore_mgo_pct: ORE_MGO%
  ore_mno_pct: ORE_MNO%
  ore_na2o_pct: ORE_NA2O%
  ore_p_pct: ORE_P%
  ore_sio2_pct: ORE_SIO2%
  ore_tio2_pct: ORE_TIO2%
  ore_tm_pct: ORE_TM%
  ore_mt: ORE_CALC_MT
  pci2_ash_pct: PCI_2_ASH%
  pci2_fc_pct: PCI_2_FC%
  pci2_im_pct: PCI_2_IM%
  pci2_vm_pct: PCI_2_VM%
  pci2_mt: PCI_2_CALC_MT
  sinter_al2o3_pct: SINTER_SP_02_AL2O3%
  sinter_cao_pct: SINTER_SP_02_CAO%
  sinter_cold_strength_ai: SINTER_SP_02_COLD_STRENGTH_AI
  sinter_cold_strength_ti: SINTER_SP_02_COLD_STRENGTH_TI
  sinter_hot_strength_ri: SINTER_SP_02_HOT_STRENGTH_RI
  sinter_fe_total_pct: SINTER_SP_02_FE(T)%
  sinter_feo_pct: SINTER_SP_02_FEO%
  sinter_hot_strength_rdi: SINTER_SP_02_HOT_STRENGTH_RDI
  sinter_k2o_pct: SINTER_SP_02_K2O%
  sinter_mgo_pct: SINTER_SP_02_MGO%
  sinter_mno_pct: SINTER_SP_02_MNO%
  sinter_na2o_pct: SINTER_SP_02_NA2O%
  sinter_p_pct: SINTER_SP_02_P%
  sinter_sio2_pct: SINTER_SP_02_SIO2%
  sinter_tio2_pct: SINTER_SP_02_TIO2%
  sinter_sp_02_basicity: SINTER_SP_02_BASICITY
  sinter_mt: SINTER_CALC_MT
  lloyds_pellet_cao_pct: LLOYDS_PELLET_PCT_CAO
  lloyds_pellet_mt: TOTAL_PELLET_CALC_MT
  lloyds_pellet_pct_al2o3: LLOYDS_PELLET_PCT_AL2O3
  lloyds_pellet_pct_fe2o3: LLOYDS_PELLET_PCT_FE2O3
  lloyds_pellet_pct_k2o: LLOYDS_PELLET_PCT_K2O
  lloyds_pellet_pct_loi: LLOYDS_PELLET_PCT_LOI
  lloyds_pellet_pct_mgo: LLOYDS_PELLET_PCT_MGO
  lloyds_pellet_pct_mno: LLOYDS_PELLET_PCT_MNO
  lloyds_pellet_pct_na2o: LLOYDS_PELLET_PCT_NA2O
  lloyds_pellet_pct_p: LLOYDS_PELLET_PCT_P
  lloyds_pellet_pct_sio2: LLOYDS_PELLET_PCT_SIO2
  lloyds_pellet_pct_tio2: LLOYDS_PELLET_PCT_TIO2
  lloyds_pellet_pct_tm: LLOYDS_PELLET_PCT_TM
  charges_per_hr: CHARGES/HRS.
  stock_rod_level: STOCKRODLEVEL
  furnace_top_gas_analysis_h2_pct: FURNACE TOP GAS ANALYSISH2%
  belly_a_c: BELLY - 15162_TEMP. OCAT-07DEG. OC
  belly_c_c: BELLY - 15162_TEMP. OC.2CT-17DEG. OC
  belly_d_c: BELLY - 15162_TEMP. OC.3DT-03DEG. OC
  bosh_a_c: BOSH - 12975_TEMP. OCAT-07DEG. OC
  bosh_b_c: BOSH - 12975_TEMP. OC.1BT-12DEG. OC
  bosh_c_c: BOSH - 12975_TEMP. OC.2CT-17DEG. OC
  bosh_d_c: BOSH - 12975_TEMP. OC.3DT-03DEG. OC
  lower_stack_a_c: LOWER STACK - 18660_TEMP. OCAT-07DEG. OC
  lower_stack_b_c: LOWER STACK - 18660_TEMP. OC.1BT-12DEG. OC
  lower_stack_c_c: LOWER STACK - 18660_TEMP. OC.2CT-17DEG. OC
  lower_stack_d_c: LOWER STACK - 18660_TEMP. OC.3DT-03DEG. OC
  ftg_uptake_avg_c: FURNACE TOP GAS_UPTAKE TEMP. OC.4AVG.DEG. OC
  ftg_uptake_bt12_c: FURNACE TOP GAS_UPTAKE TEMP. OC.1BT-12DEG. OC
  ftg_uptake_cat16_c: FURNACE TOP GAS_UPTAKE TEMP. OCAT-16DEG. OC
  ftg_uptake_ct08_c: FURNACE TOP GAS_UPTAKE TEMP. OC.2CT-08DEG. OC
  ftg_uptake_dt04_c: FURNACE TOP GAS_UPTAKE TEMP. OC.3DT-04DEG. OC
  hearth_pad_4d3_c: HEARTH PAD CENTER_TEMP. OCA4.3 MTR.DEG. OC
  hearth_pad_b5d4_c: HEARTH PAD CENTER_TEMP. OC.1B5.4 MTR.DEG. OC
  hearth_pad_c5d7_c: HEARTH PAD CENTER_TEMP. OC.2C5.7 MTR.DEG. OC
  hearth_pad_d6d1_c: HEARTH PAD CENTER_TEMP. OC.3D6.1 MTR.DEG. OC
influxdb_ml_database:
  database: ML DATASET
  measurements: rm_charge_dataset
  time_range: last 1 month