"""Emit a hand-checkable, end-to-end energy balance for one day.

Run:  python scripts/energy_balance_worked_example.py
Writes: docs/energy_balance_calculation_procedure.md

The document is GENERATED from energy_balance_phase0.build(), not written by
hand, so it cannot drift away from the code it documents. Re-run it whenever a
constant or a term changes.

The day shown is the one whose closure sits closest to the population median -
deliberately a typical day, not the best-closing one.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

import energy_balance_phase0 as eb  # noqa: E402

OUT = REPO / "docs" / "energy_balance_calculation_procedure.md"


def pick_day(df: pd.DataFrame) -> pd.Series:
    usable = df.dropna(
        subset=["closure_total", "q_topgas", "q_loss_total", "co_pct", "top_temp"]
    )
    target = usable["closure_total"].median()
    return usable.loc[(usable["closure_total"] - target).abs().idxmin()]


def f(value: float, dp: int = 1) -> str:
    return "n/a" if pd.isna(value) else f"{value:,.{dp}f}"


def main() -> None:
    df = eb.build()
    df["quarter"] = df.index.to_period("Q").astype(str)
    r = pick_day(df)
    day = r.name.date()

    L: list[str] = []
    add = L.append

    add(f"# Energy balance — worked calculation for {day}")
    add("")
    add("Generated by `scripts/energy_balance_worked_example.py` from")
    add("`energy_balance_phase0.build()`. Do not edit by hand — re-run the script.")
    add("")
    add(f"This day was chosen because its closure sits closest to the population "
        f"median ({df['closure_total'].median():.3f}) across "
        f"{int(df['closure_total'].notna().sum())} days. It is a typical day, not "
        "the best-closing one.")
    add("")
    add("Everything below is **per tonne of hot metal (tHM)** unless stated.")
    add("")

    # ---- 0. measured inputs -------------------------------------------------
    add("## 0. Measured inputs for the day")
    add("")
    add("| quantity | value | unit | source |")
    add("|---|---|---|---|")
    rows = [
        ("Hot metal produced", r["hm_mt"], "MT/day", "DPR `total_hot_metal_mt`"),
        ("Slag generated", r["slag_mt"], "MT/day", "DPR `slag_generation_mt`"),
        ("Coke charged", r["coke_mt"], "MT/day", "charge_data `coke_1/2_mt`"),
        ("Nut coke charged", r["nut_coke_mt"], "MT/day", "charge_data `nut_coke_1/2_mt`"),
        ("PCI injected", r["pci_mt"], "MT/day", "DPR `pci_mt`"),
        ("Charges", r["charges"], "per day", "charge_data row count"),
        ("Hot blast volume", r["cbv_nm3h"], "Nm³/hr", "`HOT BLAST VOLUMENM3/HR.`"),
        ("Hot blast temperature", r["blast_temp"], "°C", "`HOT BLAST TEMP.OC`"),
        ("O₂ enrichment", r["o2_enrich"], "%", "`O2 ENRICHMENT %`"),
        ("Top gas CO", r["co_pct"], "%", "influx `co_pct`"),
        ("Top gas CO₂", r["co2_pct"], "%", "influx `co2_pct`"),
        ("Top gas H₂", r["h2_pct"], "%", "influx `h2_pct`"),
        ("Top gas temperature", r["top_temp"], "°C", "influx `top_temp_avg`"),
        ("HM carbon", r["hm_c"], "%", "`CHEM_PCT_C`"),
        ("HM iron", r["hm_fe"], "%", "`CHEM_PCT_FE`"),
        ("HM silicon", r["hm_si"], "%", "`CHEM_PCT_SI`"),
        ("Slag FeO", r["slag_feo_pct"], "%", "`SLAG_PCT_FEO`"),
        ("Stave heat load, rows 6–10", r["stave_gj_per_hr"], "GJ/hr",
         "influx `heat_load_r6..10_q1..4` × 3.6"),
    ]
    for name, val, unit, src in rows:
        add(f"| {name} | {f(val, 2)} | {unit} | {src} |")
    add("")

    # ---- 1. rates -----------------------------------------------------------
    add("## 1. Convert to per-tHM rates")
    add("")
    add("```")
    add(f"coke rate      = {f(r['coke_mt'])} / {f(r['hm_mt'])} × 1000 "
        f"= {f(r['coke_rate'])} kg/tHM")
    add(f"nut coke rate  = {f(r['nut_rate'])} kg/tHM")
    add(f"PCI rate       = {f(r['pci_rate'])} kg/tHM")
    add(f"slag rate      = {f(r['slag_rate'])} kg/tHM")
    add(f"blast per tHM  = {f(r['cbv_nm3h'])} × 24 / {f(r['hm_mt'])} "
        f"= {f(r['cbv_per_thm'])} Nm³/tHM")
    add("```")
    add("")

    # ---- 2. carbon ----------------------------------------------------------
    add("## 2. Carbon actually burnt")
    add("")
    add("Carbon dissolved in the hot metal never burns, so it must be removed "
        "before crediting combustion heat. Omitting this step over-states the "
        "input by roughly 1,400 MJ/tHM.")
    add("")
    add("```")
    add(f"carbon charged  = ({f(r['coke_rate'])} + {f(r['nut_rate'])}) × "
        f"{eb.C_FRAC_COKE} + {f(r['pci_rate'])} × {eb.C_FRAC_PCI}")
    add(f"                = {f(r['carbon_charged_kg_per_thm'])} kg C/tHM")
    add(f"carbon into HM  = {f(r['hm_c'], 2)}% × 1000 "
        f"= {f(r['carbon_to_hm_kg_per_thm'])} kg C/tHM")
    add(f"carbon burnt    = {f(r['carbon_kg_per_thm'])} kg C/tHM")
    add("```")
    add("")

    # ---- 3. top gas ---------------------------------------------------------
    add("## 3. Top gas volume, from a nitrogen balance")
    add("")
    add("N₂ is inert: every Nm³ entering with the blast leaves at the top. "
        "So the top gas volume follows from measured quantities alone, with no "
        "fitted constant.")
    add("")
    n2_blast = eb.N2_IN_AIR_PCT - (r["o2_enrich"] or 0.0)
    n2_top = 100.0 - r["co_pct"] - r["co2_pct"] - r["h2_pct"]
    add("```")
    add(f"N2% in blast   = 79.2 − {f(r['o2_enrich'], 2)} = {f(n2_blast, 2)} %")
    add(f"N2% in top gas = 100 − {f(r['co_pct'], 2)} − {f(r['co2_pct'], 2)} "
        f"− {f(r['h2_pct'], 2)} = {f(n2_top, 2)} %")
    add(f"V_top          = {f(r['cbv_per_thm'])} × {f(n2_blast, 2)} / {f(n2_top, 2)}")
    add(f"               = {f(r['topgas_nm3_per_thm'])} Nm³/tHM")
    add("```")
    add("")

    # ---- 4. output ----------------------------------------------------------
    add("## 4. Output side (heat consumed and heat leaving)")
    add("")
    add("| term | formula | MJ/tHM |")
    add("|---|---|---:|")
    out_rows = [
        ("Iron oxide reduction",
         f"{eb.H_FE_REDUCTION_MJ_PER_KG} × {f(r['hm_fe'], 2)}% × 1000",
         r["q_fe_reduction"]),
        ("Top gas chemical (unburnt CO + H₂)",
         f"{f(r['topgas_nm3_per_thm'])} × (CO×{eb.CV_CO_MJ_PER_NM3} + "
         f"H₂×{eb.CV_H2_MJ_PER_NM3})/100", r["q_topgas_chemical"]),
        ("Hot metal at 1500 °C", f"{eb.H_HM_MJ_PER_T} MJ/t × 1 t",
         r["q_hm"]),
        ("Slag", f"{eb.H_SLAG_MJ_PER_KG} × {f(r['slag_rate'])}", r["q_slag"]),
        ("Shell losses (flow-scaled)", "cooling circuits", r["q_loss_total"]),
        ("Top gas sensible",
         f"{f(r['topgas_nm3_per_thm'])} × {eb.TOPGAS_CP_KJ_PER_NM3_K} × "
         f"({f(r['top_temp'])} − 25)/1000", r["q_topgas_sensible"]),
        ("Burden moisture",
         f"{eb.H_BURDEN_MOISTURE_MJ_PER_KG} × "
         f"{f(r['burden_water_kg_per_thm'])} kg H₂O", r["q_burden_moisture"]),
        ("Silicon reduction",
         f"{eb.H_SI_MJ_PER_KG} × {f(r['hm_si'], 3)}% × 1000", r["q_si"]),
        ("Manganese reduction", f"{eb.H_MN_MJ_PER_KG} × Mn%", r["q_mn"]),
        ("FeO left in slag",
         f"{eb.H_FE_TO_FEO_MJ_PER_KG} × slag FeO", r["q_feo_slag"]),
        ("Flux calcination", f"{eb.H_CO2_MJ_PER_KG} × CO₂ from LOI",
         r["q_calcination"]),
    ]
    for name, formula, val in sorted(out_rows, key=lambda x: -float(x[2] or 0)):
        add(f"| {name} | `{formula}` | {f(val, 0)} |")
    add(f"| **Total output** | | **{f(r['q_output_total'], 0)}** |")
    add("")

    # ---- 5. input -----------------------------------------------------------
    add("## 5. Input side")
    add("")
    add("| term | formula | MJ/tHM |")
    add("|---|---|---:|")
    add(f"| Carbon combustion | `{f(r['carbon_kg_per_thm'])} × "
        f"{eb.H_C_FULL_MJ_PER_KG}` | {f(r['q_carbon'], 0)} |")
    add(f"| Blast sensible heat | `{f(r['cbv_per_thm'])} × "
        f"{eb.BLAST_CP_KJ_PER_NM3_K} × ({f(r['blast_temp'])} − 25)/1000` "
        f"| {f(r['q_blast'], 0)} |")
    add(f"| **Total input** | | **{f(r['q_input'], 0)}** |")
    add("")
    add("Carbon is counted at its **full** combustion potential (C → CO₂). "
        "Whatever the furnace fails to extract leaves as unburnt CO and is "
        "booked on the output side, so the two conventions match and closure "
        "should land near 1.0.")
    add("")

    # ---- 6. closure ---------------------------------------------------------
    add("## 6. Closure")
    add("")
    add("```")
    add(f"closure = output / input = {f(r['q_output_total'], 0)} / "
        f"{f(r['q_input'], 0)} = {r['closure_total']:.3f}")
    add("```")
    add("")
    add(f"Population median closure **{df['closure_total'].median():.3f}**, "
        f"across-quarter spread **"
        f"{(df.groupby('quarter')['closure_total'].median().max() - df.groupby('quarter')['closure_total'].median().min()) / df['closure_total'].median():.1%}**.")
    add("")

    # ---- 7. constants -------------------------------------------------------
    add("## 7. Constants used")
    add("")
    add("| constant | value | unit | basis |")
    add("|---|---|---|---|")
    consts = [
        ("Slag enthalpy", eb.H_SLAG_MJ_PER_KG, "MJ/kg", "findings doc §2"),
        ("Hot metal enthalpy", eb.H_HM_MJ_PER_T, "MJ/t", "1500 °C tap, plant-stated"),
        ("Fe₂O₃ → Fe", eb.H_FE_REDUCTION_MJ_PER_KG, "MJ/kg Fe", "+824 kJ/mol Fe₂O₃"),
        ("Fe₂O₃ → FeO", eb.H_FE_TO_FEO_MJ_PER_KG, "MJ/kg Fe", "7.38 − 4.82"),
        ("Si reduction", eb.H_SI_MJ_PER_KG, "MJ/kg Si", "690 kJ/mol"),
        ("Burden moisture", eb.H_BURDEN_MOISTURE_MJ_PER_KG, "MJ/kg H₂O",
         "latent + sensible to top temp"),
        ("C → CO₂", eb.H_C_FULL_MJ_PER_KG, "MJ/kg C", "393.5 kJ/mol"),
        ("CO calorific value", eb.CV_CO_MJ_PER_NM3, "MJ/Nm³", "LHV"),
        ("H₂ calorific value", eb.CV_H2_MJ_PER_NM3, "MJ/Nm³", "LHV"),
        ("Blast cp", eb.BLAST_CP_KJ_PER_NM3_K, "kJ/Nm³·K", "standard"),
        ("Top gas cp", eb.TOPGAS_CP_KJ_PER_NM3_K, "kJ/Nm³·K", "standard"),
        ("Carbon in coke", eb.C_FRAC_COKE, "fraction", "fixed carbon"),
        ("Carbon in PCI", eb.C_FRAC_PCI, "fraction", "fixed carbon"),
        ("Heat load MW → GJ/hr", eb.HEATLOAD_MW_TO_GJ_PER_HR, "×", "measured, §units"),
    ]
    for name, val, unit, basis in consts:
        add(f"| {name} | {val} | {unit} | {basis} |")
    add("")
    add("## 8. Known open items")
    add("")
    add("1. **Shell loss drifts by quarter** when back-calculated "
        "(805 → 93 MJ/tHM). Fuel hydrogen was the leading candidate and has "
        "been **ruled out** — crediting it widens the gap at every plausible "
        "H% and barely touches the drift (712 → 652 MJ/tHM). The residual "
        "scales with total fuel, not hydrogen, so a fuel-scaled term is "
        "missing from the *output* side: top gas, dust carbon, or the "
        "direct/indirect reduction split. "
        "See `scripts/pci_hydrogen_from_closure.py`.")
    add("2. **Blast-temperature coefficient** must be derived by perturbing the "
        "closed balance, not from a one-line formula.")
    add("3. **Steam** is nil at this plant, so its energy effect cannot be "
        "calibrated from this data.")
    add("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"written: {OUT}")
    print(f"day {day}, closure {r['closure_total']:.3f}")


if __name__ == "__main__":
    main()
