-- Seed the built-in FurnaceMind quick skills into PostgreSQL.
-- This is intentionally a seed script, not a schema migration. It adapts to the
-- columns currently present in furnace_mind.skills, so optional rollout columns
-- such as qdrant_collection and created_by are used only when available.

DO $$
DECLARE
    present_columns text[];
    metadata_column text;
    row_exists boolean;
    skill record;
    cols text[];
    vals text[];
    updates text[];
BEGIN
    SELECT array_agg(column_name::text)
    INTO present_columns
    FROM information_schema.columns
    WHERE table_schema = 'furnace_mind'
      AND table_name = 'skills';

    IF present_columns IS NULL THEN
        RAISE NOTICE 'Skipping FurnaceMind skill seed: furnace_mind.skills does not exist.';
        RETURN;
    END IF;

    IF NOT 'skill_id' = ANY(present_columns) THEN
        RAISE NOTICE 'Skipping FurnaceMind skill seed: furnace_mind.skills.skill_id does not exist.';
        RETURN;
    END IF;

    FOR skill IN
        SELECT *
        FROM (VALUES
            (
                'skill_optimise_unit_cost',
                'Unit Cost',
                '₹',
                'Compare recent operating state against best-shift cost targets.',
                'Use the Unit Cost skill prompt generated by SkillEngine and the configured best-shift benchmark context. Do not execute arbitrary code from database content.',
                'built_in',
                TRUE,
                NULL,
                '{"slug":"optimise","symbol":"₹","order":10,"handler":"optimise_prompt","display_template":"Unit Cost - last 30 days vs best-shift targets","context_files":["SKILLS_BESTSHIFT.md","SKILLS_OPTIMISE.md"]}'
            ),
            (
                'skill_shift_to_best',
                'Shift to Best',
                '↗',
                'Compare the last completed shift against best-shift targets.',
                'Use the Shift to Best skill prompt generated by SkillEngine and the configured best-shift benchmark context. Do not execute arbitrary code from database content.',
                'built_in',
                TRUE,
                NULL,
                '{"slug":"shift_to_best","symbol":"↗","order":20,"handler":"shift_to_best_prompt","display_template":"Shift to Best: {shift_date}, Shift {shift_label}","context_files":["SKILLS_BESTSHIFT.md"]}'
            ),
            (
                'skill_heatloads',
                'Heatloads',
                '🔥',
                'Check recent heatload and skin-temperature behavior.',
                'Use the Heatloads skill prompt generated by SkillEngine and the configured heatload context. Do not execute arbitrary code from database content.',
                'built_in',
                TRUE,
                NULL,
                '{"slug":"heatload","symbol":"🔥","order":30,"handler":"heatload_prompt","display_template":"Heatloads - last 8h vs 2-month baseline","context_files":["SKILLS_HEATLOAD.md"]}'
            )
        ) AS seeded(
            skill_id,
            name,
            symbol,
            description,
            instruction,
            source_type,
            is_active,
            created_by,
            metadata_text
        )
    LOOP
        cols := ARRAY['skill_id'];
        vals := ARRAY[format('%L', skill.skill_id)];
        updates := ARRAY[]::text[];

        IF 'name' = ANY(present_columns) THEN
            cols := array_append(cols, 'name');
            vals := array_append(vals, format('%L', skill.name));
            updates := array_append(updates, format('name = %L', skill.name));
        END IF;


        IF 'symbol' = ANY(present_columns) THEN
            cols := array_append(cols, 'symbol');
            vals := array_append(vals, format('%L', skill.symbol));
            updates := array_append(updates, format('symbol = %L', skill.symbol));
        END IF;
        IF 'description' = ANY(present_columns) THEN
            cols := array_append(cols, 'description');
            vals := array_append(vals, format('%L', skill.description));
            updates := array_append(updates, format('description = %L', skill.description));
        END IF;

        IF 'instruction' = ANY(present_columns) THEN
            cols := array_append(cols, 'instruction');
            vals := array_append(vals, format('%L', skill.instruction));
            updates := array_append(updates, format('instruction = %L', skill.instruction));
        END IF;

        IF 'source_type' = ANY(present_columns) THEN
            cols := array_append(cols, 'source_type');
            vals := array_append(vals, format('%L', skill.source_type));
            updates := array_append(updates, format('source_type = %L', skill.source_type));
        END IF;

        IF 'qdrant_collection' = ANY(present_columns) THEN
            cols := array_append(cols, 'qdrant_collection');
            vals := array_append(vals, 'NULL');
            updates := array_append(updates, 'qdrant_collection = NULL');
        END IF;

        IF 'is_active' = ANY(present_columns) THEN
            cols := array_append(cols, 'is_active');
            vals := array_append(vals, CASE WHEN skill.is_active THEN 'TRUE' ELSE 'FALSE' END);
            updates := array_append(
                updates,
                'is_active = ' || CASE WHEN skill.is_active THEN 'TRUE' ELSE 'FALSE' END
            );
        END IF;

        IF 'created_by' = ANY(present_columns) THEN
            cols := array_append(cols, 'created_by');
            vals := array_append(vals, format('%L', skill.created_by));
            updates := array_append(updates, format('created_by = %L', skill.created_by));
        END IF;

        FOREACH metadata_column IN ARRAY ARRAY['metadata', 'metadata_json']
        LOOP
            IF metadata_column = ANY(present_columns) THEN
                cols := array_append(cols, metadata_column);
                vals := array_append(vals, format('%L', skill.metadata_text));
                updates := array_append(
                    updates,
                    format('%I = %L', metadata_column, skill.metadata_text)
                );
            END IF;
        END LOOP;

        IF 'created_at' = ANY(present_columns) THEN
            cols := array_append(cols, 'created_at');
            vals := array_append(vals, 'NOW()');
        END IF;

        IF 'updated_at' = ANY(present_columns) THEN
            cols := array_append(cols, 'updated_at');
            vals := array_append(vals, 'NOW()');
            updates := array_append(updates, 'updated_at = NOW()');
        END IF;

        EXECUTE format(
            'SELECT EXISTS (SELECT 1 FROM furnace_mind.skills WHERE skill_id = %L)',
            skill.skill_id
        ) INTO row_exists;

        IF row_exists THEN
            IF array_length(updates, 1) > 0 THEN
                EXECUTE format(
                    'UPDATE furnace_mind.skills SET %s WHERE skill_id = %L',
                    array_to_string(updates, ', '),
                    skill.skill_id
                );
            END IF;
        ELSE
            EXECUTE format(
                'INSERT INTO furnace_mind.skills (%s) VALUES (%s)',
                array_to_string(cols, ', '),
                array_to_string(vals, ', ')
            );
        END IF;
    END LOOP;
END $$;